### ISSUE TITLE
Animation lag when using interactive dismissal

### ISSUE THREAD

**Issue by lm2s** [nathantannar4/InputBarAccessoryView#103]
I've been experiencing an animation lag (also mentioned in issue #46) when using the InputBarAccessoryView subview method and tracked it down to the way the drag is handled.  
 
The `func handlePanGestureRecognizer(recognizer: UIPanGestureRecognizer)` (in KeyboardManager: 289) calls the `callbacks[.willChangeFrame]?(keyboardNotification)` closure which itself calls the  `func animateAlongside(_ notification: KeyboardNotification, animations: @escaping ()->Void)` from `func bind(inputAccessoryView: UIView) -> Self`.  
 
The lag occurs because the `cachedNotification` has duration of 0.25, which is then used by `animateAlongside` and results in the visual lagging.  
The fix for this issue is simply removing the `animateAlongside` and directly applying the `keyboardHeight` to the constraint constant and calling `layoutIfNeeded`.  

A better fix, I believe, would be to separate the drag gesture handler to its own function (it currently reuses the `keyboardWillChangeFrame(notification:)` that is also used by the corresponding keyboard notification) and either not call `animateAlongside` or call it with a duration of 0s.

I can submit a PR with this fix, but first would like to get some input/opinions regarding this before since it's weird that not many persons are experiencing this.

EDIT: actually an easier fix is just changing `timeInterval` to _var_ in KeyboardNotification and setting it to 0 on the `handlePanGestureRecognizer`

**Comment by nathantannar4** [comment]
Thanks for a detailed write up. Perhaps the default animation duration should be 0 if the notification does not provide a time interval 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lm2s** [comment]
I don't think that would solve the issue, because (contrary to my assumption) the `keyboardDidShowNotification` comes with a 0.25 duration on the `userInfo`.

I've created a video showcasing the issue: https://send.firefox.com/download/4303586a597ac62f/#4m3Cw_yLJIOZbNT8e2Z5SA

**Comment by nathantannar4** [comment]
@lm2s Mind making a PR? @austinwright Can help get it merged in 😊

**Comment by AndrewSB** [comment]
I'm seeing this as well, I'm patching my fork of this library, I'll try to submit a PR
