### ISSUE TITLE
Adding a hashtag after a mention doesn't change the prefix.

### ISSUE THREAD

**Issue by imclean** [nathantannar4/InputBarAccessoryView#108]
After I enter a mention (@user) and select the user, I keep typing and then add a hashtag (#tag) the prefix should change to a # but it is still a @ so doesn't pick up any tags.

Try typing "Hey @User what about a #hashtag"

the autocompleteManager.currentSession?.prefix is still @ and never changes

**Comment by zilppuri** [comment]
Any plans for a fix? Or does someone have a good workaround until this is fixed?
The bug is easy to reproduce in the Example app by typing @ and then after autocompletion following with #.

**Comment by thomassnielsen** [comment]
There's a workaround here: https://github.com/nathantannar4/InputBarAccessoryView/pull/111

If you use Cocoapods you can link to that fix by using 

```rb
pod 'InputBarAccessoryView', git: 'https://github.com/thomassnielsen/InputBarAccessoryView.git', commit: 'ce7f871f3191c9f6d70e69503e8ed8a315c4bb52'
```

We've been using this fix in production for a while now.
