### ISSUE TITLE
InputBarAccessoryView overlaps navigationbar in landscape orientation

### ISSUE THREAD

**Issue by nasserprofessional** [nathantannar4/InputBarAccessoryView#12]
**The InputBarAccessoryView overlaps navigationbar in landscape orientation.**

I was testing MessageKit on my iPhone 7 and noticed a problem with the MessageInputBar overlapping the navigationbar so that lead me to testing the InputBarAccessoryView example on my iPhone 7 as well and they both have the same problems.

**Steps to reproduce the issue:**
1. Launch Example project in portrait
2. Start typing and press return on the keyboard to create multiple lines
3. Rotate to landscape

**The InputBarAccessorryView is now overlapping the navigationbar:**
![b98cd441-3990-4efa-92c6-84fab15446ee](https://user-images.githubusercontent.com/476105/32680108-17a8903a-c661-11e7-951e-9144b1b439c4.png)

**I was also able to reproduce this issue in the iOS Simulator with the following steps:**
1. Launch Example project in portrait
2. Press return multiple times to create multiple lines
3. Rotate to landscape
4. Make the keyboard visible if it isnt showing

The InputBarAccessorryView is now overlapping the navigationbar

**Comment by nasserprofessional** [comment]
I was trying to fix the issue and I managed to fix it Im not sure if this is the best way to do it but heres how Iv fixed it:

Iv added an NSNotification.Name.UIKeyboardDidChangeFrame notification in viewDidLoad and then changed the maxTextViewHeight in the notification:

```
override func viewDidLoad() {
        super.viewDidLoad()

        NotificationCenter.default.addObserver(
            self,
            selector: #selector(keyboardChangedFrame),
            name: NSNotification.Name.UIKeyboardDidChangeFrame,
            object: nil
        )
}


    @objc func keyboardChangedFrame(_ notification: Notification) {
        if let keyboardFrame: NSValue = notification.userInfo?[UIKeyboardFrameEndUserInfoKey] as? NSValue {
        let keyboardRectangle = keyboardFrame.cgRectValue
            let keyboardHeight = keyboardRectangle.height
            
            
            
            let height = UIApplication.shared.statusBarFrame.height +
                self.navigationController!.navigationBar.frame.height
            self.bar.maxTextViewHeight = UIScreen.main.bounds.size.height - keyboardHeight - height + self.bar.inputTextView.frame.size.height
      
        }
    }
```

**Comment by nathantannar4** [comment]
Hi @nasserprofessional 

I changed the default `maxTextViewHeight` in the latest release. If you want finer control then yes your method can work for dynamic adjustment
