### ISSUE TITLE
How to customize the message bubbles?

### ISSUE THREAD

**Issue by orkhanalizade** [nathantannar4/InputBarAccessoryView#120]
Hi, is there a way to customize the message bubbles?
I'm working on it more than a day but cannot customize it. I want to achieve this result:

<img width="236" alt="Screenshot 2020-03-27 at 19 17 29" src="https://user-images.githubusercontent.com/7026025/77787392-c6ef5880-705f-11ea-8b8d-49d9da343b5c.png">

If you would help me I would be so grateful!
Thanks in advance!

Somehow my 

`func messagePadding(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIEdgeInsets`

method also NOT being called. But I set all the delegates.
Thanks in advance!

**Comment by nathantannar4** [comment]
Did you mean to make this issue in MessageKit?

**Comment by Kaspik** [comment]
Most probably wrong repo, closing.
