### ISSUE TITLE
How to hide the inputBarAccessoryView and display it only when a user taps a button

### ISSUE THREAD

**Issue by dnawarrior** [nathantannar4/InputBarAccessoryView#122]
I want to hide the inputaccessoryview by default or when the user taps outside it. If the user is scrolling the table it should be hidden and only visible when tapped on a button,how can this be done?

**Comment by nathantannar4** [comment]
See: https://github.com/nathantannar4/InputBarAccessoryView/blob/master/Sources/ViewControllers/InputBarViewController.swift

**Comment by dnawarrior** [comment]
Thank you so much!
I used 
`inputBar.inputTextView.becomeFirstResponder()
`
and commented out
/      override var canBecomeFirstResponder: Bool {
//            return true
//        }
