### ISSUE TITLE
A way to set custom cell for autocomplete manager

### ISSUE THREAD

**Issue by uuttff8** [nathantannar4/InputBarAccessoryView#127]
Now, when iOS 13 brings Dark Mode, UIColor.white should appear less and less in code, but your library is hardcoded to use only white background color https://github.com/nathantannar4/InputBarAccessoryView/blob/60a295fc312e0b347fb35220dab436bf6ca03bd1/Sources/Plugins/AutocompleteManager/AutocompleteManager.swift#L65

is it a way to use custom cell for autocomplete manager or it should be done in future?

**Comment by uuttff8** [comment]
https://github.com/nathantannar4/InputBarAccessoryView/blob/60a295fc312e0b347fb35220dab436bf6ca03bd1/Sources/Plugins/AutocompleteManager/AutocompleteManager.swift#L63

**Comment by nathantannar4** [comment]
Yes there is a method on the data source. You just need to implement it 😊

**Comment by Kaspik** [comment]
@uuttff8 Did you check 5.0.0 release, is this still an issue? :)

**Comment by uuttff8** [comment]
@Kaspik issue is disappeared in 5.0v, yes, thx
