### ISSUE TITLE
Issue after closing keyboard 

### ISSUE THREAD

**Issue by xsoti** [nathantannar4/InputBarAccessoryView#130]
After I close keyboard by calling resignFirstResponder() on inputTextView or becomeFirstResponder() on ViewController I got error "rejected resignFirstResponder when being removed from hierarchy". It wouldn't be so bad but when I set keyboardAppearance to .dark it became white during hiding.

I added code for hiding keyboard to Project Example: [download](https://drive.google.com/file/d/1OT44balQ1W41IwyPds2C6qPe4fPtNO-k/view?usp=sharing)
Changes are only on CommonTableViewController.swift file so you can check what I'm talking about.

**Comment by nathantannar4** [comment]
I have a subclass of UIViewController in this framework that shows how you correctly hide/show. Can you try that method?

**Comment by xsoti** [comment]
Hey nathantannar4

I have check READMEPreviewViewController which subclass from InputBarViewController and it has this same issue I described above.

**Comment by hamzaozturk** [comment]
I have checked Example project and it also gives same warning.

```
Example[32232:602841] [View] First responder warning: <InputBarAccessoryView.InputTextView: 0x7fca50079600;
baseClass = UITextView; frame = (0 0; 330 38); text = '';
clipsToBounds = YES;
gestureRecognizers = <NSArray: 0x60000147d200>;
layer = <CALayer: 0x600001a05200>; contentOffset: {0, 0};
contentSize: {28, 36.5}; adjustedContentInset: {0, 0, 0, 0}>
rejected resignFirstResponder when being removed from hierarchy
```

It also gives the same warning message when you dismiss keyboard in interactive mode.

**Comment by Leta0n** [comment]
Seems that issue also causes small ui freeze after keyboard is dismissed

**Comment by Leta0n** [comment]
Does anyone has any progress here?

**Comment by nathantannar4** [comment]
No longer seeing this warning from the example project. 

This issue has become stale/outdated. Please re-open if desired.
