### ISSUE TITLE
TopStackView Issue

### ISSUE THREAD

**Issue by hamzaozturk** [nathantannar4/InputBarAccessoryView#132]
I added a view to topStackView using the code and it works well:

```
topStackView.insertArrangedSubview(replyManager.replyView, at: topStackView.arrangedSubviews.count)
topStackView.layoutIfNeeded()
```

![Simulator Screen Shot - iPhone 11 - 2020-06-25 at 13 20 04](https://user-images.githubusercontent.com/6054248/85701949-995d8e00-b6e6-11ea-95d3-1cc655faadc5.png)

When i remove the view using the code below it creates a weird situation. It brings the barView to the left of the inputbarView.

```
topStackView.removeArrangedSubview(replyManager.replyView)
topStackView.layoutIfNeeded()
```

![Simulator Screen Shot - iPhone 11 - 2020-06-25 at 13 20 43](https://user-images.githubusercontent.com/6054248/85702043-af6b4e80-b6e6-11ea-9b41-a779d9e64e9d.png)

The reply view used:

```
open class ReplyView: UIView {
    lazy var barView: UIView = { [weak self] in
        let view = UIView()
        view.backgroundColor = .red
        return view
    }()
    
    lazy var closeButton: UIButton = { [weak self] in
        let button = UIButton()
        button.setAttributedTitle(NSMutableAttributedString().bold("X", fontSize: 15, textColor: .white), for: .normal)
        button.setAttributedTitle(NSMutableAttributedString().bold("X", fontSize: 15, textColor: UIColor.white.withAlphaComponent(0.5)), for: .highlighted)
        button.layer.cornerRadius = 10
        button.clipsToBounds = true
        button.backgroundColor = UIColor(red: 0, green: 122/255, blue: 1, alpha: 1)
        button.addTarget(self, action: #selector(deleteMessage), for: .touchUpInside)
        return button
    }()
    
    weak var manager: ReplyManager?
    
    var intrinsicContentHeight: CGFloat = 60 {
        didSet {
            invalidateIntrinsicContentSize()
        }
    }
    
    open override var intrinsicContentSize: CGSize {
        return CGSize(width: 0, height: intrinsicContentHeight)
    }
    
    override init(frame: CGRect) {
        super.init(frame: .zero)
        setup()
    }
    
    required public init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    func setup() {
        backgroundColor = .yellow
        
        setupSubviews()
        setupConstraints()
    }
    
    private func setupSubviews() {
        
        addSubview(barView)
        addSubview(closeButton)
    }
    
    private func setupConstraints() {
        
        NSLayoutConstraint.activate([
            closeButton.centerYAnchor.constraint(equalTo: centerYAnchor)
        ])
        
        barView.addConstraints(topAnchor, left: leftAnchor, bottom: bottomAnchor, widthConstant: 4)
        closeButton.addConstraints(right: rightAnchor, rightConstant: 8)
    }
    
    @objc
    func deleteMessage() {
        manager?.removeMessage()
    }
}
```

**Comment by kinoroy** [comment]
`removeArrangedSubview(_ view: UIView)` removes the view from the stack view's list of managed views, but it **does not** remove it from the view hierarchy. https://developer.apple.com/documentation/uikit/uistackview/1616235-removearrangedsubview 

You can simply call `replyManager.replyView.removeFromSuperview()`to remove it from the view hierarchy and the stack view will remove it from its arranged views automatically. Alternatively, you can set the view's `isHidden` property to `true` which will prevent the view from appearing on screen but keep it in the list of subviews.

**Comment by aberguno** [comment]
this is how i fixed it....but idk if it is the correct way

topStackView.removeArrangedSubview(attachmentManager.attachmentView)
attachmentManager.attachmentView.removeFromSuperview()
topStackView.layoutIfNeeded()
messageInputBar.invalidateIntrinsicContentSize()
