### ISSUE TITLE
is this bug ? inputAccessory conflict with SVPROGRESSHUD

### ISSUE THREAD

**Issue by fukemy** [nathantannar4/InputBarAccessoryView#135]
Hello, i have a question because i can not explain why this problem appear on my app, but you can see my video here.
https://streamable.com/8zx8v4

When alert showed, the input bar go hide
When i press ok, the input bar show then i called network function to reconnect with signalr, using SVProgressHUD to block user interaction in screen.
3 When SVProgressHUD go hide, the input bar go hide too, i can not know why

**Comment by fukemy** [comment]
hi, i found out that because i called view.endEditting(true) from parentVC, comment this line then it's work normal, but i still can not know why it's cause input bar go hide

**Comment by Kaspik** [comment]
It depends how you add then input bar to the controller. endEditting means resign responder which might hide the input view for you.

I don't think we are able to help you more, we use SVProgressHUD in our apps too and we don't have this issue.
