### ISSUE TITLE
Jumpy `inputAccessoryView ` when used in a UIViewController but not when in UITableViewController

### ISSUE THREAD

**Issue by brod-ie** [nathantannar4/InputBarAccessoryView#14]
The `inputAccessoryView` jumps up and down when used in a `UIViewController` but not when in `UITableViewController`/`UICollectionViewController `

You can recreate this by simply changing [the Example](https://github.com/nathantannar4/InputBarAccessoryView/tree/master/Example/Example) to a `UIViewController`.

I'm using ASyncDisplayKit's `ASCollectionNode` instead of UIKit's collection view for performance, therefore I'm using a `UIViewController`. Have I missed something or are there any known solutions for this?

![jumpy](https://user-images.githubusercontent.com/1520630/35100199-cd2ef210-fc52-11e7-8cd3-d49afdd8cf5b.gif)

**Comment by nathantannar4** [comment]
Are you trying to animate the size transition? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brod-ie** [comment]
Doh! I just forked the example to test further in a fresh environment and couldn't for the life of me recreate. It turns out it was [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager)! I'd enabled it from my AppDelegate. It must disable itself when the frontmost VC is a `UITableViewController`/`UICollectionViewController` 🤔

My apologies, 👍 great module!
