### ISSUE TITLE
AutocompleteManager doesn't unregisterCurrentSession when an AutocompleteSession has already been inserted

### ISSUE THREAD

**Issue by codie1991** [nathantannar4/InputBarAccessoryView#144]
Not too sure if this is intentional and by design, or a bug,  however I've had issues with the `AutocompleteManager` not ending the session once tapping on an `AutocompleteSession` cell.

The issue appears to be with the `reloadData()` method.

Once a prefix has been detected and the default value for `keepPrefixOnCompletion` as true, an `AutocompleteSession` has been inserted with the prefix. This always results in `let query = textView?.find(prefixes: autocompletePrefixes, with: delimiterSet)` having a value, and therefore skips the guard else block that performs the `maxSpaceCountDuringCompletion` check.

The UI renders and looks correct, the right delegate methods are called to hide and show the `AutocompleteManager` tableview, but if a breakpoint is added to the `func autocompleteManager(_ manager: AutocompleteManager, shouldRegister prefix: String, at range: NSRange) -> Bool` inside of the example project you'll notice it keeps triggering even after a session was selected. 

The simplest way to break this behaviour is to set `keepPrefixOnCompletion` to false. 
Alternatively I guess the delegate is an area to try breakout of this.

Hope this helps anyone that may come across the problem, and happy to be told I'm being an idiot and missed something.

**Comment by nathantannar4** [comment]
I'm trying to understand if there is a possible bug here. When a cell is selected, `autocomplete(with session: AutocompleteSession) ` will be called which if all goes well, calls `unregisterCurrentSession()` at the end. Then as long as the delegate allows it, the session is ended. Are you seeing something different?

**Comment by HakanSAYAR** [comment]
@codie1991 thanks for this answer.

**Comment by nathantannar4** [comment]
This issue has become stale/outdated. Please re-open if desired.
