### ISSUE TITLE
Hiding the input text view

### ISSUE THREAD

**Issue by brod-ie** [nathantannar4/InputBarAccessoryView#15]
In some scenarios, we'd like the input bar to contain buttons only. Is there a way to collapse/hide the middle stack view?

**Comment by nathantannar4** [comment]
Hmm interesting, that's not what I had intended it for but I believe this could be accomplished by adding a width constraint of 0 to the InputTextView. I don't think that will break any auto layout. Let me know 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brod-ie** [comment]
Progress!

```
let inputTextViewWidth = NSLayoutConstraint(item: bar.inputTextView, attribute: .width, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1, constant: 0)
bar.addConstraint(inputTextViewWidth)

bar.setLeftStackViewWidthConstant(to: screenSize.width, animated: false)
bar.setRightStackViewWidthConstant(to: 0, animated: false)
bar.setStackViewItems([InputBarButtonItem().configure({
    $0.setTitle("Contact Us", for: .normal)
    $0.backgroundColor = UIColor.green
})], forStack: .left, animated: false)
```

However, there appears to be spacing between the now collapsed input text view and the left stack view:
![simulator screen shot - iphone 8 - 2018-01-26 at 14 14 04](https://user-images.githubusercontent.com/1520630/35443506-3b41894c-02a3-11e8-803a-fdc8be09f332.png)

The left stack view spacing is 8pt, whereas the gap to the right of it is 20pt. How can I remove these insets? There also appears to be vertical padding above/below the left/right stack views and input text view.

**Comment by brod-ie** [comment]
Further to this, when I remove the constraint and clear the stack views, the input text view stays 0pt wide (I've tried forcing relayout with `setNeedsLayout()` then `layoutIfNeeded()` on the input text view and on the bar itself)
```
bar.setLeftStackViewWidthConstant(to: 0, animated: false)
bar.setRightStackViewWidthConstant(to: 32, animated: false)
bar.setStackViewItems([], forStack: .left, animated: false)
bar.setStackViewItems([bar.sendButton], forStack: .right, animated: false)

if let inputTextViewWidth = inputTextViewWidth {
     bar.removeConstraint(inputTextViewWidth)
}
```

**Comment by nathantannar4** [comment]
Ya to remove the spacing try adjusting the InputTextViewPadding. And to your next question, try invalidating the intrinsicContentSize

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Any luck?

**Comment by brod-ie** [comment]
Boom that worked 😀 Final issue to sort out, despite setting `bar.padding = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)`, there's still a 6pt top padding on the bar? (If I increase the height of the `InputBarButtonItem` the 6pt padding persists)

![simulator screen shot - iphone 8 - 2018-01-30 at 13 54 08](https://user-images.githubusercontent.com/1520630/35570318-c5bc9b86-05c6-11e8-89e4-a76a4fdfdc93.png)

**Comment by nathantannar4** [comment]
Did you zero out the InputTextViewPadding and the topTextViewPadding? Also, if all you want us a single button you might be better off overloading the InputAccessoryView of the ViewController to a button

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brod-ie** [comment]
I've set `topStackViewPadding` to `UIEdgeInsets.zero` to no avail. Where is the getter/setter for `InputTextViewPadding` or `topTextViewPadding `? I like this system as the input bar dynamically updates based on the Chat state (e.g. matched, unmatched, etc.)

**Comment by junestchick** [comment]
Hi, I just want to animate inputTextView height to 0. How can i do it?

**Comment by nathantannar4** [comment]
@junestchick there is no built in support for that currently. You could try adding a height contraint of 0 to it but I'm not sure if that would have other side effects you do not desire. What is the layout youre trying to achieve

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by junestchick** [comment]
> @junestchick there is no built in support for that currently. You could try adding a height contraint of 0 to it but I'm not sure if that would have other side effects you do not desire. What is the layout youre trying to achieve
> 
> Sent with [GitHawk](http://githawk.com)

I want it like google assistant. When press keyboard button, keyboard and input textview are shown and when dismiss keyboard, input textview is hidden. 
https://itunes.apple.com/us/app/google-assistant/id1220976145?mt=8

**Comment by nathantannar4** [comment]
@junestchick I have updated the API in version 4.2 to allow the replacement of the `InputTextView` with any other view. This new view that you set will need to self size itself with constraints or an intrinsic content size. To get the `InputTextView` back just set it as the middleContentView.

`setMiddleContentView(_ view: UIView?, animated: Bool)`

See also the updated example: https://github.com/nathantannar4/InputBarAccessoryView/blob/master/Example/Example/InputBarExamples/NoTextViewInputBar.swift

![simulator screen shot - iphone xs - 2018-11-21 at 23 14 43](https://user-images.githubusercontent.com/15272998/48887228-5f7a2680-ede3-11e8-87c0-d71041795554.png)

**Comment by nathantannar4** [comment]
@brod-ie This should make it easier for you too 😊

**Comment by junestchick** [comment]
> @brod-ie This should make it easier for you too 😊

Thank you so mucchhh! You made my day!!!

**Comment by brod-ie** [comment]
@nathantannar4 You're the man!
