### ISSUE TITLE
API error: <_UIKBCompatInputView; frame = (0 0; 0 0);> returned 0 width, assuming UIViewNoIntrinsicMetric

### ISSUE THREAD

**Issue by AndrewSB** [nathantannar4/InputBarAccessoryView#154]
Thank you for all the work with this library.

I'm trying to switch my input bar from being a subview to the `inputAccessoryView` of my `UIViewController.UIView` subclass. I'm getting the following error: 

```
API error: <_UIKBCompatInputView: 0x7f80cb98a640; frame = (0 0; 0 0); layer = <CALayer: 0x600000d07c20>> returned 0 width, assuming UIViewNoIntrinsicMetric
```

which causes the input accessory view to disappear below the screen.

It seems to have something to do with whether the view controller's `translatesAutoresizingMaskIntoConstraints` is set or not, I'm trying a couple different versions to see what might be causing this. I couldn't find an issue/documentation about this, I was wondering if it was a well-known issue when using the `UIView.inputAccesoryView` and if so, how to debug it?

**Comment by Kaspik** [comment]
Did you check the Example project first, is it happening there as well? :)

**Comment by AndrewSB** [comment]
It isn't happening in the example, I imagine it's some interaction with the constraints that I set in the parent view. I haven't got around to producing a reduced case yet, I might do that if I can't figure out the problem

**Comment by AndrewSB** [comment]
Ahh, I found the root issue. This happens when you add the `InputBarAccessoryView` as a subview and set it as your view's `inputAccessoryView`.
You have to choose one or the other.

Hope this helps anyone else who runs into this issue
