### ISSUE TITLE
Question/Bug: Animate send button

### ISSUE THREAD

**Issue by AndrewSB** [nathantannar4/InputBarAccessoryView#157]
Hey! I was trying to animate the send button in a bar to hide when the bar is empty and show when it isn't.

Animations to hide and show out of a stack view (the `rightStackView` in this case) can be hard, It looks like if I try to hide and show the send button, it appears from the left edge of the stack view. I'd like to instead have it appear from the center of it's final position with a spring animation. In regular UIKit maybe something like 

```swift
// earlier
sendButton.frame.size = .zero

// to show:
let finalSize = CGSize(width: 32, height: 32)
sendButton.center = CGPoint(x: rightStackView.origin.x - (finalSize.width / 2)
UIView.animate ... {
   sendButton.frame.size = finalSize
}
```

when I run this, the sendButton jumps around instead of growing from the center. Any ideas? If this isn't clear, I can add an example to the Example app

Thanks!

**Comment by AndrewSB** [comment]
I've created #159 to help come to an answer together.
There are 2 outstanding issues with the example that I'd love help with:

1. The dismissal animation doesn't animate to the right ending position 
2. I can't use a spring animation. Putting `sendButton.setSize(newSize, animated: false)` into a `UIView.animate` animation results in an instant change

**Comment by AndrewSB** [comment]
cc @Kaspik

**Comment by Kaspik** [comment]
I'm not sure if you can animate sizes that easily, wouldn't opacity animation be enough? Or do you want to hide it and make the text field bigger then? What's the reason for that, if typing anything into the text field shows it again immediately?

**Comment by qwertygeneral** [comment]
To add to this -- I've noticed that it does not seem to be possible to animate _any_ subviews (not just the sendButton) of the InputBarAccessoryView? I am able to make discrete changes like imageButton.alpha = 0.5, but if I try to wrap it inside a UIView.animate {} block and a non-zero duration, the animations all execute instantaneously. 

I am trying to make one of the buttons in my InputBarAccessoryView exhibit a glowing/pulsating effect (using .repeat and .autoReverse), and nothing is happening.

**Comment by AndrewSB** [comment]
Yeah, that's what I've seen too. I've resigned to not doing nice animations in my text field for now, but I'd love to add them as soon as this can be prioritized and figured out!

**Comment by Kaspik** [comment]
I believe button animation example is now added / merged, not sure if this is still an issue, but closing and let me know. :)
