### ISSUE TITLE
Customize delete button for AttachmentCell

### ISSUE THREAD

**Issue by MattiaConfalonieri** [nathantannar4/InputBarAccessoryView#16]
Hi, how I can customize delete button for AttachmentCell?

**Comment by nathantannar4** [comment]
Hi Mattiea,

Great question. Conform to `AttachmentManagerDataSource` and then add the method
`func attachmentManager(_ manager: AttachmentManager, cellFor attachment: AttachmentManager.Attachment, at index: Int) -> AttachmentCell`

You can get the default cell via `manager.attachmentView.dequeueReusableCell(withReuseIdentifier: ImageAttachmentCell.reuseIdentifier, for: indexPath) as? ImageAttachmentCell`

Just be sure to assign the necessary properties like:
```swift
cell.attachment = attachment
cell.indexPath = indexPath
cell.manager = self
cell.imageView.image = image
```

You can also make your own cells by subclassing `AttachmentCell`

**Comment by AndrewSB** [comment]
fwiw: it would be useful to add "You can get the default cell via `manager.attachmentView.dequeueReusableCell(withReuseIdentifier: ImageAttachmentCell.reuseIdentifier, for: indexPath) as? ImageAttachmentCell`" to the docs

**Comment by monstermac77** [comment]
> Great question. Conform to `AttachmentManagerDataSource` and then add the method `func attachmentManager(_ manager: AttachmentManager, cellFor attachment: AttachmentManager.Attachment, at index: Int) -> AttachmentCell`

Thanks so much, I was spending hours in subclass hell trying to just change the "x" to be a little icon. But I'm having trouble figuring out which of my classes to conform to AttachmentManagerDataSource and implement the method. Each one I do, it seems like the cellFor method isn't being called. As many others probably are, I'm using this alongside MessageKit and I've tried on my main view (`MessagesViewController`) and some of my other input bar related classes like 
`CameraInputBarAccessoryView`. What class should conform to `AttachmentManagerDataSource`?
