### ISSUE TITLE
DarkMode 

### ISSUE THREAD

**Issue by KennethLee95** [nathantannar4/InputBarAccessoryView#162]
Hi I found an issues regarding the dark mode, textview text color will become white while user current theme is dark mode while when user switch back to normal mode, textview text color back to black. Have tried inputBar.inputTextView.textColor but no clue.

**Comment by Kaspik** [comment]
Hey, I have honestly no idea what's going on from your description. Can you give us examples, code, screenshots etc?
Thanks
