### ISSUE TITLE
what's make wrong color? wrong autocomplete table layout  color

### ISSUE THREAD

**Issue by fukemy** [nathantannar4/InputBarAccessoryView#168]
Hello, i can not find the line of code to force set color of autocompeletextview color? Can u help? The color is difference between ios12 and 14 as image[here](https://user-images.githubusercontent.com/8202437/96819417-b95f4d00-144d-11eb-8933-907bd813fabf.png)

**Comment by nathantannar4** [comment]
It's the textLabel property of the autocomplete cell.

**Comment by fukemy** [comment]
thanks, im wrong when try to set label textcolor but it use attribute text
