### ISSUE TITLE
"shouldRegister" triggered again

### ISSUE THREAD

**Issue by HakanSAYAR** [nathantannar4/InputBarAccessoryView#169]
Hi, 
I integrated this library into my project but I have a problem;

**Steps**
1. I register the "@" prefix.
2. I type "@Hakan" and select "@Hakan" from the list.
3. `shouldComplete` method triggered and "@Hakan" entered on the textView.
4. If I add anything more in the text, the `shouldRegister` method triggered again.

This is not what I want. When the user selects a user from the list, the `shouldUnregister` method should be triggerred. 
If I writes the "@" prefix again, the `shouldRegister` method should be triggered.

I added this code line to fix the bug;
`manager.keepPrefixOnCompletion = false` so the `shouldRegister` method does not trigger again.
But if I do this and select a user from the list, "Hakan" entered on the textView, not "@Hakan".

When I select a user from the user list for example "@Hakan" (so when the "shouldComplete" method is triggered), it should write "@Hakan" and the `shouldRegister` method **should not be triggered until the user enters the "@" prefix again.**
How can I solve this?

**Comment by Kaspik** [comment]
Hey! Thanks for bringing this up. If you are able to repro it in our example project (or create a new one if it's not there), and you believe it's a bug, feel free to open a PR together with the example and we will be more than happy to review it! :)

**Comment by HakanSAYAR** [comment]
Hi @Kaspik ,
Do I need to open a PR? Your sample project already works like this. If you test the scenario I mentioned, I think you can see the problem. Thanks!

**Comment by Kaspik** [comment]
Ideally open a PR with solution / fix that you think is the right one so we can take a look! :)

**Comment by HakanSAYAR** [comment]
I don't know the solution. Only I posted the problem I encountered. I don't know the solution. I just posted the problem I encountered. Also I sent you the test scenario about problem. Are these not enough?

**Comment by nathantannar4** [comment]
> If I add anything more in the text, the shouldRegister method triggered again

This is expected behaviour. It gives more flexibility to have 1 autocomplete start another autocomplete. For example, a user autocompleted "race" and them now "racecar" should be suggested.
