### ISSUE TITLE
Any tap into the textfield when pasteboard has an image we get an iOS 14 paste notification

### ISSUE THREAD

**Issue by alexjameslittle** [nathantannar4/InputBarAccessoryView#175]
**Describe the bug**
iOS 14 introduced a privacy notification when apps access UIPasteBoard, this notification is appearing even if we don't handle image pasting because the library is accessing the image property before handling the image

**To Reproduce**
Copy an image into your paste board from photos etc, then tap into the input text view with imagePaste disabled

**Expected behavior**
This notification should not appear until the image has been pasted

**Screenshots**

**Environment**
- What version of InputBarAccessoryView are you using? 5.2.0
- What version of iOS are you running on? iOS 14.1
- What version of Swift are you running on? 5.3
- What device(s) are you testing on? Are these simulators? XS Max
- Is the issue you're experiencing reproducable in the example app? 

**Additional context**
`if action == NSSelectorFromString("paste:") && UIPasteboard.general.image != nil`
I believe it would be sufficient enough to not access the image property of pasteboard here

**Comment by Kaspik** [comment]
Hey! Would you mind opening a PR and testing it on our example project? :)

**Comment by alexjameslittle** [comment]
Hey

Yeah sure, I tested in the example app just now and it exists in there too

Will open a PR today :)
