### ISSUE TITLE
Just one attachment

### ISSUE THREAD

**Issue by MattiaConfalonieri** [nathantannar4/InputBarAccessoryView#18]
if you set 

showAddAttachmentCell = false 

because you want just 1 attachment

and press again the StackViewItems second attachment is added.

How can i set a maximum of 1 attachment or disable the StackViewItems wen one attachment is added?

**Comment by nathantannar4** [comment]
Hi @MattiaConfalonieri it doesn't support max attachments out of the box. You will need to write some logic to determine if the add button should be enabled or disabled. I suggest using the AttachmentManagerDelegate to hook into when attachments are removed and added 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattiaConfalonieri** [comment]
Thanks for reply, I resolve with user interaction enable

`func setAttachmentManager(active: Bool) {
        let topStackView = inputBar.topStackView
        if active && !topStackView.arrangedSubviews.contains(attachmentManager.attachmentView) {
            topStackView.insertArrangedSubview(attachmentManager.attachmentView, at: topStackView.arrangedSubviews.count)
            inputBar.leftStackView.isUserInteractionEnabled = false
            topStackView.layoutIfNeeded()
        } else if !active && topStackView.arrangedSubviews.contains(attachmentManager.attachmentView) {
            topStackView.removeArrangedSubview(attachmentManager.attachmentView)
            inputBar.leftStackView.isUserInteractionEnabled = true
            topStackView.layoutIfNeeded()
        }
    }`

**Comment by nathantannar4** [comment]
Nice! I would suggest disabling the button itself as it will show a different tint colour to let a user know they can’t tap it. Just disabling user interaction could frustrate users unless you have some other info message letting them know

**Comment by MattiaConfalonieri** [comment]
UHHHHHHH this is a great suggestion... thanks...

**Comment by hem091** [comment]
I have done this way to disable button after adding 1 attachment:

func attachmentManager(_ manager: AttachmentManager, didReloadTo attachments: [AttachmentManager.Attachment]) {
        **for item in inputBar.bottomStackViewItems {
            if let itm = item as? InputBarButtonItem {
                itm.isEnabled = !(manager.attachments.count > 0)
            }
        }**
        inputBar.sendButton.isEnabled = manager.attachments.count > 0
    }
