### ISSUE TITLE
Attachment didSelect not working

### ISSUE THREAD

**Issue by EngrAhsanAli** [nathantannar4/InputBarAccessoryView#180]
Hello,

Thanks for providing this opensource useful library. I'm sure it's really helpful for many iOS/Mac applications.

I just wanted to highlight an issue with the attachments selection section. The following check fails since the indexPath.row will start from 0 and array count from 1. Hence, no delegate method is triggering upon users' click.

```
final public func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        // if indexPath.row == attachments.count 

}
```

**Comment by Kaspik** [comment]
I believe `indexPath.row` `0` is `addAttachment` cell == cell with plus sign to add a new attachment, thus not selectable. :)
