### ISSUE TITLE
Blur issue during pop gesture or animation.

### ISSUE THREAD

**Issue by crousselle2** [nathantannar4/InputBarAccessoryView#181]
**Describe the bug**
I have been tracking this issue down for a while now but the blur view is not rendering properly when a pop gesture or pop animation is triggered. 
The blur effect suddenly disappears, only leaving the background visible, which looks pretty terrible in most cases. 

**To Reproduce**
Steps/code to reproduce the behavior:
Display an `InputBarAccessoryView` with the blur enabled, trigger a pop gesture on the screen while the accessory view is visible. 
This (ugly) example shows this behavior quite clearly

```swift
final class BrokenInputBar: InputBarAccessoryView {
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        configure()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    private func configure() {
        self.isTranslucent = true
        backgroundView.backgroundColor = .clear
        contentView.backgroundColor = .clear
        blurView.effect = UIBlurEffect(style: .light)
    }   
}
```

**Expected behavior**
Blur should stay visible during pop. 

**Screenshots**
<img width="560" alt="Correct Blur" src="https://user-images.githubusercontent.com/45021389/102278870-5df68c00-3edf-11eb-9e2b-d5df5fe2539a.png">
<img width="560" alt="Incorrect Blur during pop" src="https://user-images.githubusercontent.com/45021389/102278881-618a1300-3edf-11eb-8691-e8b6b8abe199.png">

**Environment**
- InputBarAccessoryView 5.2.2
- iOS 13.x and 14.x are affected
- 5.0
- Simulator + iPhone 12 Pro + iPhone X Max
- Is the issue you're experiencing reproducable in the example app? No, I do not see a use of the blur in the example app.

**Comment by nathantannar4** [comment]
Hmm, not sure why this is happening at this moment

**Comment by Kaspik** [comment]
@crousselle2 May I ask you to either drop here super simple example in zip or add another example type to our example project via PR to have it there, be able to debug from my side, and also to keep it there for future reference so it doesn't break again? It would save me a lot of time building the setup.

Thanks!
