### ISSUE TITLE
Manual keyboard dismiss is not animated

### ISSUE THREAD

**Issue by Janneman84** [nathantannar4/InputBarAccessoryView#186]
I noticed that the keyboard closing slide animation does not work, but it just disappears instantly. The README Preview of the example app does the same thing when you hit Send. 

However if you close the keyboard by swiping it down it animates just fine (like in the other examples of the example app).

Same result with using `inputTextView.resignFirstResponder()`, `inputTextView.isEditable=false` or doing `becomeFirstResponder()` on the VC.

I can't find any mentions of this issue anywhere surprisingly. Is it just me?

**Comment by Kaspik** [comment]
Still happening?

**Comment by Janneman84** [comment]
I just tested it again with the latest version and it seems to work perfectly now, thanks!
