### ISSUE TITLE
pasted url then autocomplete table show blank

### ISSUE THREAD

**Issue by fukemy** [nathantannar4/InputBarAccessoryView#187]
https://user-images.githubusercontent.com/8202437/105927422-88a73900-6076-11eb-852e-e5697684b6c5.MP4
hi, can u help me about this? Only copy link cause this problem, trying to insert/delete 1 text then it's disappear

**Comment by Kaspik** [comment]
Did you resolve this? If not, is it happening on our examples? If not, can you create one please?

**Comment by fukemy** [comment]
first time I think the white view is top stack's view, but it's not. i tracked the topstack tableview in autocompletetext class but can not find anything cause this white space.  I dont know what it is, i have to remove autocompletemanager from textinput so that disapear

**Comment by Kaspik** [comment]
Does it happen on Example projects here?

**Comment by fukemy** [comment]
i just tested example project, it's work fine, may be the inputbarAccessory from MessageKit  is  old, now im trying to update it to test, thanks
