### ISSUE TITLE
Is it possible to retain InputBarAccessoryView frame?

### ISSUE THREAD

**Issue by StackHelp** [nathantannar4/InputBarAccessoryView#188]
Is it possible to retain the `InputBarAccessoryView` frame from the bottom for e.g. some view below accessory view (not a `UITabBar`)? 

If relevant, please let us know the following things:

- What version of InputBarAccessoryView are you using? 5.1.0
- What version of iOS are you running on? iOS 14.0
- What version of Swift are you running on? 5.3
- What device(s) are you testing on? Are these simulators? iPhone 7 / iPhone 11
- Is the issue you're experiencing reproducable in the example app? I made another app for that and here is the [link](https://github.com/BhavinBhadani/AlineaUI/tree/InputAccessory)

You can also check a [video](https://filebin.net/z20wdg7lvffi5buu). 

One more thing is can we add options above `UITextView` rather than the bottom like zoom? 
![File](https://user-images.githubusercontent.com/41230403/106275456-dfba3300-625b-11eb-8863-469f19cca337.jpg)

**Comment by Kaspik** [comment]
Video no available...
