### ISSUE TITLE
messageInputBar go hide when window alert show? how to disable it?

### ISSUE THREAD

**Issue by fukemy** [nathantannar4/InputBarAccessoryView#189]
Hi, thanks for great library, i dont want to hide messageInputBar when showing windowAlert,... can u give me some advance? Thanks

**Comment by WineKai** [comment]
> Hi, thanks for great library, i dont want to hide messageInputBar when showing windowAlert,... can u give me some advance? Thanks

I also encountered this problem. Have you solved it?

**Comment by fukemy** [comment]
sorry i still not solved this :(

**Comment by WineKai** [comment]
I searched for a while and found a similar:https://stackoverflow.com/questions/46996251/inputaccessoryview-animating-down-when-alertcontroller-actionsheet-presented.
I used several different system versions to test and found that this problem only occurs on iOS14

**Comment by fukemy** [comment]
hi, not only action sheet, present something may cause keyboard go hide, or somethings,.. because keyboard is added to rootWindow, so anything with higher window level may make keyboard disappear( u can view debug hierarchy to see what happen). after a lot of search decided that is normal action of my app kk

**Comment by WineKai** [comment]
yeah, I tracked the code and found that when a new window is displayed, the willMove(toSuperview newSuperview: UIView?) of inputbarAccessoryView will be triggered. At this time, the newsuperView is nil, so deactivateConstraints() will be executed, causing the inputBarAccessoryView to hide. I thought of a trick，make the keyWindow becomeFirstResponder when the new window hidden, code this:
`

		if let window = UIApplication.shared.delegate?.window {
			window?.makeKey()
			window?.becomeFirstResponder()
		}
`
Currently testing on my side is normal

**Comment by fukemy** [comment]
hi, i found ur mention code
```
open override func willMove(toSuperview newSuperview: UIView?) {
        super.willMove(toSuperview: newSuperview)
        guard newSuperview != nil else {
            deactivateConstraints()
            return
        }
        activateConstraints()
    }
```
can i ask when u put this below code:
```
	if let window = UIApplication.shared.delegate?.window {
		window?.makeKey()
		window?.becomeFirstResponder()
	}
```

**Comment by WineKai** [comment]
I thought about it last night, maybe my solution can't solve your bug.
I have a floating button on a new higher-level window, similar to the iPhone’s AssistiveTouch. When the floating button is clicked, the inputbarAccessoryView will be hidden. When the click is over, the inputbarAccessoryView will not appear automatically, and it will appear after clicking on other parts of the screen. So I added the code above after clicking the floating button. In this way, when you click the floating button, the inputbarAccessoryView will still be hidden, but it will appear automatically when release my finger.
The reason why inputbarAccessoryView is hidden is that the first responder is transferred to the new window, which causes inputbarAccessoryView to respond to resignFirstResponder. If you want to prevent the inputbarAccessoryView from hiding when the new window is displayed, I haven't thought of how to solve it for the time being.

**Comment by fukemy** [comment]
hey, u can use my button like me, any modify it to look like button that u want to be

https://github.com/fkalai/FloatButtonToScroll

this floatingbutton is normal working with same window level because it were added to view as subview
```
scrollBottomBtn.setTargetView(view: view)
```

![Screen Shot 2021-03-26 at 13 54 37](https://user-images.githubusercontent.com/8202437/112593967-d05dfd00-8e3a-11eb-9550-9bd45278e454.png)

**Comment by yarodevuci** [comment]
any updates on this?

**Comment by fukemy** [comment]
the inputbar auto hide when contect menu show, ifaik.

**Comment by gerchicov-vg** [comment]
The same is for `SKStoreReviewController`:
https://github.com/nathantannar4/InputBarAccessoryView/issues/266
And it doesn't depend on cursor inside input bar
