### ISSUE TITLE
Text input maximum number of lines

### ISSUE THREAD

**Issue by andrewlord1990** [nathantannar4/InputBarAccessoryView#19]
How do you set the text input to only grow to a maximum number of lines before it becomes scrollable instead.

I have seen the ability to set the maximum height of the view, however, this value is automatically set at certain places in the code.

To set the max height height to 3 lines, I currently have the following.

```swift
        inputBar.shouldAutoUpdateMaxTextViewHeight = false
        inputBar.maxTextViewHeight = 70
```

However, the `maxTextViewHeight` can be set back to default by a method for if the view moves to a new window. Not sure when this might happen though.

Do you know if the above is the best way of achieving this? Or if there is a nicer way?

**Comment by nathantannar4** [comment]
Hi @andrewlord1990 what you have is the intended method of preventing growth over a given height. Are you saying it's not working?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrewlord1990** [comment]
It works.

Mainly, because I am altering a property that the class itself can also alter, I just wanted to confirm this was the correct way of doing it, without the class overwriting the value I have set.

For example, I can see the maxTextViewHeight is set when the view is moved to a new window regardless of whether `shouldAutoUpdateMaxTextViewHeight` is true or not.

Therefore, my reasoning for opening the issue was to check with you (or someone who knew) whether changing the property as I had was the correct way of doing it.

Is it worth separating the internal maximum height and user maximum height into two properties. This way the boolean for whether to update it wouldn't be required and the library would never be writing to the same property as user's might be setting. I think this would be clearer in the API and also more future proof (i.e. less likely for a future change to overwrite the user's maximum height value in any situation).

Happy to look into a PR at some point, however, it would be a breaking change to API, so wanted to ask your thoughts first.

**Comment by nathantannar4** [comment]
Im sorry I don't understand your 2 property suggestion, it is already in two properties. One being a boolean
```swift
/// A boolean that determines if the `maxTextViewHeight` should be auto updated on device rotation
    open var shouldAutoUpdateMaxTextViewHeight = true
    
    /// The maximum height that the InputTextView can reach. Automatically set with `calculateMaxTextViewHeight()`
    open var maxTextViewHeight: CGFloat = 0
```

Are you saying that the way I've commented it is confusing?

**Comment by andrewlord1990** [comment]
Sorry for the confusion, it was hard to describe.

What I was trying to suggest, was the library maintaining a maximum height value based on screen-size and orientation as it is now. However, instead of using a boolean property to turn this behaviour on and off, I was suggesting a second height float property that the user sets, then the one the library automatically sets can be internal (private).

This would mean the user just sets a single value (an optional height float) and the API is slightly more discoverable. It also means the user knows the library will never overwrite their preference in any situation. I think it just separates library and user logic without the need for the user to know to turn the library's behaviour off.

However, I can see it is just a different opinion on implementing a similar concept, so I can understand that their may not be a big enough benefit to changing it and forcing users of the library to change their code after updating.

With regards to the other suggestions I was making:

1) The comment on maxTextViewHeight says it is set automatically, which as a user of the API suggests to me I shouldn't set it as my value will be automatically overwritten. I think changing this comment to mention it is set automatically if "shouldAutoUpdateMaxTextViewHeight" is true might be clearer. I can submit a PR to do that.

2) maxTextViewHeight is set when the view is moved to another window. Will this only ever happen when the view is created, or could it happen later and overwrite the max height I will have set? As in that place it doesn't check shouldAutoUpdateMaxTextViewHeight.

**Comment by nathantannar4** [comment]
Sure open to seeing a PR on your optional max height CGFloat. Will evaluate it to see if it's more API friendly. Don't know if you noticed but I also just added the ability to force set max height

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrewlord1990** [comment]
Okay thanks. Sorry for the long-winded description!

Did you see my question (number 2) above?

**Comment by nathantannar4** [comment]
Hmm. I haven’t thoroughly tested it but I thought that should only be called once. Nevertheless I’ll do the bool check in my next update

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrewlord1990** [comment]
Okay thanks for all your help. Will close the issue.
