### ISSUE TITLE
inputTextView font & textColor has no effect

### ISSUE THREAD

**Issue by asad-appifytech** [nathantannar4/InputBarAccessoryView#191]
**Describe the bug**
I am trying to changed textColor of inputTextView also I want to change the font. I tried with given functions but it's not applying the font to the textView. Although, placeholder gets the font but not the textview itself.

**To Reproduce**
Steps/code to reproduce the behavior:

```swift
self.inputBarView.inputTextView.placeholder = "Type message..."
self.inputBarView.inputTextView.font = UIFont(name: "Muli-SemiBold", size: 14.0)
self.inputBarView.inputTextView.textColor = .blue
self.inputBarView.inputTextView.tintColor = .blue
```

**Expected behavior**
inputTextView font should get changed.

**Environment**
- What version of InputBarAccessoryView are you using? 5.2.3
- What version of iOS are you running on? 14.2
- What version of Swift are you running on? 5.2
- What device(s) are you testing on? Are these simulators? iPhone XS Max

**Comment by nathantannar4** [comment]
If you are using the AutocompleteManager these will be overwritten as it sets attributed strings. See `defaultTextAttributes` in the AutocompleteManager instead.

**Comment by asad-appifytech** [comment]
Thanks for your swift reply. That really solved my issue.
