### ISSUE TITLE
(BUG)inputaccessoryview disappear when typing UIImagePickerController keyboard

### ISSUE THREAD

**Issue by fukemy** [nathantannar4/InputBarAccessoryView#196]
hi, it hard to explain this problem, but when i present icloud share view, typing in this keyboard, the inputaccessoryview still not dismissed

but when typing in searchbar inside UIImagePickerController, when dismiss the inputaccessoryview disapear. here is the video i captured:

https://vimeo.com/user84971345/review/522782434/ed7687d806

**Comment by Kaspik** [comment]
Video not available.

**Comment by fukemy** [comment]
sorry i updated video link: 
https://vimeo.com/522782434

**Comment by Kaspik** [comment]
Can you add the video here? Still can't watch without registering for Vimeo. 😄

**Comment by nathantannar4** [comment]
This issue has become stale/outdated. Please re-open if desired.
