### ISSUE TITLE
Image attachment upload progress UI for AttachmentCollectionView

### ISSUE THREAD

**Issue by toshi0383** [nathantannar4/InputBarAccessoryView#202]
**Is your feature request related to a problem? Please describe.**

We'd like to show upload progress of each (image) attachments.

**Describe the solution you'd like**

Add built in support in this library, so this library becomes even more awesome.

**Describe alternatives you've considered**

Dig down subviews tree, find ImageAttachmentCell to cover with progress indicator or something. (haven't tried)

**Additional context**

I'd like to do something like this.

<img width="559" alt="スクリーンショット 2021-04-21 21 16 40" src="https://user-images.githubusercontent.com/6007952/115552126-e3070d00-a2e6-11eb-988c-182eeb190b0c.png">

**Comment by Kaspik** [comment]
I don't think this should be a built-in feature, though you can easily do it already right now with current implementation if you just extend the functionality.

The reason why I don't think this should be built in is that IBAV shouldn't know anything about network, data, upload, or anything else - it's up to you to manage it

**Comment by toshi0383** [comment]
Hi @Kaspik, Thanks for the feedback!

>  you can easily do it already right now with current implementation if you just extend the functionality.

Could you please give us a little bit more detail?
As a new comer of this library, it's not clear for us how to extend `AttachmentCollectionView`'s functionality.

**Comment by fukemy** [comment]
create collectionview then add to topstackview
