### ISSUE TITLE
How to custom layout contentView

### ISSUE THREAD

**Issue by nthnhung23** [nathantannar4/InputBarAccessoryView#208]
<img width="938" alt="Screen Shot 2021-05-24 at 14 53 27" src="https://user-images.githubusercontent.com/75512024/119315877-7fcf1880-bca0-11eb-93e1-39daac71c630.png">

I want to custom layout like this, but I can't change middleContentView, inputBarView to small.

I have made like above:
<img width="607" alt="Screen Shot 2021-05-24 at 15 04 23" src="https://user-images.githubusercontent.com/75512024/119316752-86aa5b00-bca1-11eb-82a8-5defcb9ef5c8.png">

How to help me fill send button to the bottom contentView's?

**Comment by Kaspik** [comment]
Still a problem? I guess you need to fill the image in the button.

```swift
button.contentMode = .scaleAspectFit
button.contentHorizontalAlignment = .fill
button.contentVerticalAlignment = .fill
 ```
