### ISSUE TITLE
Input bar disappear when have another textfield

### ISSUE THREAD

**Issue by MattiaConfalonieri** [nathantannar4/InputBarAccessoryView#21]
Hi, i have a bug little complicate to explain 

I have a textfield in the view where I use the InputBarAccessoryView

When I select this textfield, InputBarAccessoryView disappear as I expect, but when I resignFirstResponder my texfield and keyboard disappear   InputBarAccessoryView is gone and never come back again... Any suggestion?

**Comment by nathantannar4** [comment]
Sounds like you need to call `becomeFirstResponder()` on the view controller. ViewController must be the first responder for an inputAccessoryView to appear

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattiaConfalonieri** [comment]
YESSS

        self.becomeFirstResponder()

Is the answer after dismiss keyboard forms my textfield...

thanks

**Comment by javiergomezgit** [comment]
Thanks, self.becomeFirstResponder() did the job.
