### ISSUE TITLE
'shared' is unavailable in application extensions for iOS (Xcode 13 Beta 4)

### ISSUE THREAD

**Issue by CQuerido** [nathantannar4/InputBarAccessoryView#213]
Hello everyone,

I switched to Xcode 13 Beta 4 and now I have this error which prevents me from going further, I have already looked for several solutions on Google but unfortunately none of them worked.

Who would have the solution or an update? I specify that I use SPM

Thank you all in advance

<img width="275" alt="Capture d’écran 2021-07-28 à 02 33 27" src="https://user-images.githubusercontent.com/88065327/127244830-3aaaa2e3-e5a9-497b-aa94-e81b205571d4.png">

<img width="1101" alt="Capture d’écran 2021-07-28 à 02 33 11" src="https://user-images.githubusercontent.com/88065327/127244833-a9cbc9c8-6e3b-4d72-be47-6e3340f5e383.png">

**Comment by Kaspik** [comment]
We are aware of this but we are not working on XCode 13 yet. We will definitely fix it later in August before September comes. :)

**Comment by CQuerido** [comment]
Super thank you for the quick feedback so I will wait for the next update. Thanks again
