### ISSUE TITLE
create recorder view like whatsapp 

### ISSUE THREAD

**Issue by ahmedfadl1993** [nathantannar4/InputBarAccessoryView#214]
is there a way to create or customize audio recorder view like whatsapp? 

<img width="288" alt="Screen Shot 2021-07-30 at 12 20 46 AM" src="https://user-images.githubusercontent.com/74156895/127573091-649dfdfe-d10c-417f-9725-3839ec5cba7a.png">

**Comment by fukemy** [comment]
hide messageInputBar and show your customBar with audio button like this
