### ISSUE TITLE
InputBarAccessoryView suddenly shows up where it shouldn't after using the power button or taking a screenshot

### ISSUE THREAD

**Issue by Janneman84** [nathantannar4/InputBarAccessoryView#219]
I'm using MessageKit. When my chat VC presents a VC as a pagesheet the InputBarAccessoryView goes away, which is good. However if you then power off the device then turn it back on the InputBarAccessoryView is suddenly on screen. Alternatively, when you take a screenshot and then touch the thumbnail in the corner the InputBarAccessoryView shows up too.

You can easily recreate this yourself. I added a little bit of code to the MessageKit example app. Add the following to ChatViewController.swift's viewDidLoad():

```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
    let vc = UIViewController.init()
    vc.view.backgroundColor = .red
    vc.modalPresentationStyle = .pageSheet //or use .formSheet, .overFullScreen, .overCurrentContext
    self.present(vc, animated: true)
}
```

All it does is showing a plain red VC shortly after the chat is on screen.

Then:
- start the MessageKit example app 
- choose Basic Example (or any other)
- activate the text field to pop up the keyboard
- wait for the red VC to pop up
- press the power button, then turn device back on and unlock (works in simulator too)
- InputBarAccessoryView is on screen, while it shouldn't
- instead of using the power button, make a screenshot instead, then touch the thumbnail in the corner of the screen (only works on physical device)

Notice the issue only occurs if the text field is activated before presenting the VC (step 3)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/9085167/138276715-d458a60f-ca82-4f18-8ade-ec7a22a935e0.gif)

**Comment by fukemy** [comment]
did u check with real device?

**Comment by Janneman84** [comment]
Yes I it occurs on a real device device just as well. In fact as I stated in the last bullet the bug can also be triggered by taking a screenshot _on a real device_, (making screenshots doesn't work in simulator, since you can't press power and volume buttons at once).

So yes.

**Comment by Janneman84** [comment]
Would somebody like to give this a try? The issue occurs also in the example app of this repo. To trigger it add the following to READMEPreviewViewController.swift:
```    
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    inputBar.inputTextView.becomeFirstResponder()
    DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
        let vc = UIViewController.init()
        vc.view.backgroundColor = .red
        self.present(vc, animated: true)
    }
}
```

Then start the app and pick README Preview (top one). You'll see the keyboard pop up and then a red VC pops up as a page sheet. You'll see that the InputAccessoryView is not visible now. Now turn off the device with the power button, then turn it back on and unlock the device. You'll see that the InputAccessoryView is now visible on top of the red VC, which is wrong.

**Comment by fukemy** [comment]
Hi, did u tried to close keyboard before present new VC?

**Comment by Janneman84** [comment]
Closing the keyboard first prevents this issue yes, that's how I avoid it now.

But it's not ideal so it'd be nice if this issue would be addressed.

**Comment by fukemy** [comment]
it's seem the owner avoid your problem, i have same problem, all the time open newVC, or sheet,... i always check if keyboard isFirstResponder then dismiss it before do other action

**Comment by Janneman84** [comment]
Most users of this package are not aware of this issue and don't have the habit you have. They all potentially end up with users facing this issue, literary getting stuck in apps in some cases. I was fortunate enough to find out about it myself so I could deal with it.

Just that there is a way to prevent the issue doesn't take away the fact that this still is a bug.

**Comment by nathantannar4** [comment]
InputBarAccessoryView doesn't observe view controller presentation/dismissal. Its appearance on screen is purely based on UIKit's handling for a UIViewController's `inputAccessoryView`. This is dependent on the UIViewController being the "first responder".

This issue could potentially be an enhancement in MessageKit, since the `MessagesViewController` would be able to auto resign first responder.
