### ISSUE TITLE
Compatible with PIPKit

### ISSUE THREAD

**Issue by fukemy** [nathantannar4/InputBarAccessoryView#220]
Hi, as using chatApp with call function, we want to minimize callVC to take user easy to do anything what they want. So i chosen PipKit(https://github.com/Kofktu/PIPKit)

 As current code, i added CallVC as ***ChildViewController***, it's work normally without messageinputbar problem, when changed to using PipKit, it's add CallVC as subview into window, so it's make problem with messageInputBar 

I want to ask can i solved this? I dont know why messageInputBar does not disappear

**Comment by Kaspik** [comment]
You have ot override the inputBarAccessoryView for the owner controller.
