### ISSUE TITLE
When installing MessageKit using SPM, inputBarAccessoryView enters a fetching loop

### ISSUE THREAD

**Issue by Camelot93** [nathantannar4/InputBarAccessoryView#221]
Hello, 

I am using SPM as a dependency manager for my Xcode project. When adding MessageKit package using the URL github.com/MessageKit/MessageKit, Xcode enters a fetching loop when trying to retrieve inputBarAccessoryView where it:

-Fetches inputBarAccessoryView
-resolve packages
-updates Messagekit
-clone inputBarAccessoryView
-remove inputBarAccessoryView

And repeats

the Error encountered during this process is 
invalid custom path 'Sources' for target 'InputBarAccessoryView'

Environment Xcode
Dependency manager SPM
Version of MessaggeeKit that i am trying to get is the same as master

**Comment by Kaspik** [comment]
Not able to repro.
