### ISSUE TITLE
Hello, how do I implement a custom emoji keyboard? Similar to WeChat.

### ISSUE THREAD

**Issue by CainLuo** [nathantannar4/InputBarAccessoryView#225]
Hello, how do I implement a custom emoji keyboard? It's similar to WeChat, this problem has been bothering me for a long time, but it seems that because of the inputAccessoryView provided by UIKit, I can only customize it myself, right?

![IMG_3662](https://user-images.githubusercontent.com/8857291/148575677-0b8e52f8-6dd8-4104-a786-4e0519de40c3.jpg)

![IMG_3663](https://user-images.githubusercontent.com/8857291/148575683-fe6117c4-0819-4234-bc73-ecb7c7226c6f.jpg)

**Comment by CainLuo** [comment]
> Put in your own custom UIView that has UICollectionView instead of keyboard, and load whatever content of the collection view you want.

I'm sorry, I didn't express myself accurately enough, I know how to implement the custom UIView at the bottom, in fact I want to know how to move the InputBarAccessoryView to the corresponding position when the custom UIView at the bottom comes out, because the KeyboardManager in the source code is listening to the relevant notifications, if I want to achieve the effect in the figure, do I need to rewrite the relevant notification methods?

**Comment by feiyu92** [comment]
> > Put in your own custom UIView that has UICollectionView instead of keyboard, and load whatever content of the collection view you want.
> 
> I'm sorry, I didn't express myself accurately enough, I know how to implement the custom UIView at the bottom, in fact I want to know how to move the InputBarAccessoryView to the corresponding position when the custom UIView at the bottom comes out, because the KeyboardManager in the source code is listening to the relevant notifications, if I want to achieve the effect in the figure, do I need to rewrite the relevant notification methods?

enum FBKeyboardType {
    case text
    case emoji
    case more
}
...
var keyboardType: FBKeyboardType = .text
...
let button = InputBarButtonItem()
            .onTouchUpInside { item in
                self.keyboardType = self.keyboardType == .text ? .more : .text
                self.inputTextView.inputView = self.keyboardType == .more ? UIView(frame: CGRect(x: 0, y: 0, width: 375, height: 228)) : nil
                self.inputTextView.reloadInputViews()
            }

**Comment by rgmyyw** [comment]
老铁,  这个问题最后又解决吗?  我已经弹出键盘了, 是可以切换的,  但是,如果当前键盘是隐藏的, 弹出不了更多面板
```swift
inputTextView.inputView = nil
inputTextView.inputView = moreView
inputTextView.reloadInputViews()
inputTextView.inputView?.becomeFirstResponder
```

**Comment by xiaomage1478** [comment]
Hello, do you know how inputTextView parses custom emoticons? For example, [dog] can be parsed as 🐶
