### ISSUE TITLE
InputBarAccessoryView + SwiftUI incorrect offset

### ISSUE THREAD

**Issue by Kaspik** [nathantannar4/InputBarAccessoryView#236]
Transferring an issue from MessageKit: https://github.com/MessageKit/MessageKit/issues/1734

---

**Describe the bug**

When you come to enter a message, the `InputBarAccessoryView` pushes up so that the keyboard can be shown. This works correctly in the Simulator, but not on device. The messages get blocked in behind. See screenshot attached.

**To Reproduce**

Run the Example app on device, select **SwiftUI Example**, try to send a message.

**Expected behavior**

The messages are shown _above_ the `InputBarAccessoryView` like they do with the other examples or when running in the Simulator.

**Screenshots**

![Screen Shot 2022-08-10 at 12 46 37 PM](https://user-images.githubusercontent.com/104395039/183981210-56f7a400-5f96-4d33-9f61-0981f18f8f86.png)

**Environment**
- What version of MessageKit are you using? **Latest main branch** - https://github.com/MessageKit/MessageKit/commit/14dd6aa335e76c46a06db7e9ee5c1d62a0ccca6a
- What version of iOS are you running on? **15.4.1**
- What version of Swift are you running on? **Swift 5**
- What device(s) are you testing on? Are these simulators? **iPhone 11 Pro (device), iPhone 13 Pro (simulator)**
- Is the issue you're experiencing reproducible in the example app? **Yes**

**Comment by e1block** [comment]
Solved. See https://github.com/MessageKit/MessageKit/issues/1734#issuecomment-1221426408
