### ISSUE TITLE
Library crashes app when adding an attachment when an AttachmentManager dataSource is defined 

### ISSUE THREAD

**Issue by sgraesser17** [nathantannar4/InputBarAccessoryView#237]
**Describe the bug**
My app crashes on iOS 15.5 when adding attachments when an AttachmentManager dataSource is defined

**To Reproduce**
Add the following code to the CommonTableViewController.swift file
After line 29:
```swift
		manager.dataSource = self
```

After line 250
```swift
extension CommonTableViewController: AttachmentManagerDataSource {
	func attachmentManager(_ manager: AttachmentManager, cellFor attachment: AttachmentManager.Attachment, at index: Int) -> AttachmentCell {
		let indexPath = IndexPath(row: index, section: 0)
		
		// Only images are supported by default
		switch attachment {
		case .image(let image):
			guard let cell = manager.attachmentView.dequeueReusableCell(withReuseIdentifier: ImageAttachmentCell.reuseIdentifier, for: indexPath) as? ImageAttachmentCell else {
				fatalError()
			}
			cell.attachment = attachment
			cell.indexPath = indexPath
			cell.manager = manager
			cell.imageView.image = image
			return cell
			
		default:
			return manager.attachmentView.dequeueReusableCell(withReuseIdentifier: AttachmentCell.reuseIdentifier, for: indexPath) as! AttachmentCell
		}
	}
}
```
Compile and run the example app.
Select the Slack row in the InputAccessoryView section
Tap on the photo library button
Select a photo
App crashes at line 205 in AttachmentManager.swift file with a "Fatal error: Index out of range"

**Expected behavior**
I expected the photo to be added as an attachment

**Screenshots**
None

**Environment**
- What version of InputBarAccessoryView are you using? 5.5
- What version of iOS are you running on? 15.5
- What version of Swift are you running on? 5.5
- What device(s) are you testing on? Are these simulators? On a Simulator
- Is the issue you're experiencing reproducable in the example app? Yes

**Additional context**
Replace line 205 with the following code:
```swift
        if indexPath.row == attachments.count && showAddAttachmentCell {
            return nil
        }
        
        let attachment = attachments[indexPath.row]
        if let customSize = self.dataSource?.attachmentManager(self, sizeFor: attachment, at: indexPath.row){
```

**Comment by nathantannar4** [comment]
Does not crash for me. Please clearly list all reproduction steps.

**Comment by sgraesser17** [comment]
Don't know what else to tell you. The app crashes every time for me. The index path row is 1 and the attachments array has only 1 item in it. Since showAddAttachmentCell is true, the collection view has increased in the number of items in the section by 1. But, the collection view isn't checking if the last cell in the section is for the add attachment cell. The method is automatically assuming the index path row is smaller than the attachment array size.

<img width="1512" alt="Screen Shot 2022-10-06 at 11 27 23 AM" src="https://user-images.githubusercontent.com/47432786/194390631-2a3ea3f9-fcf9-447e-8f43-10c4c59b3505.png">

**Comment by mmdock** [comment]
got the same crash.  my team is using messagekit on version 3.8.0 (just updated to this version in our latest release).  Now, it looks like we need to revert back to 3.7.0.  the update to inputbaraccessoryview 5.5 caused this for us as well.

**Comment by Kaspik** [comment]
@mmdock 3.8.0 is quite old too, did you try 4.0.0? Any hint or idea how to repro or when it happens? Did you repro in the example project?

**Comment by mmdock** [comment]
@monstermac77  @Kaspik @nathantannar4  still having this crash while trying to update to 6.2.0.  I can't add any attachment.  

the issue seems to come from

      if let customSize = self.dataSource?.attachmentManager(self, sizeFor: self.attachments[indexPath.row], at: indexPath.row){
            return customSize
        }

it looks like the row value is 1 greater than the actual number of attachments on inspection

**Comment by monstermac77** [comment]
Thanks so much for fixing this with 6.3.0! Been working great for us.
