### ISSUE TITLE
Layout issues on iPad when using pagesheets

### ISSUE THREAD

**Issue by Janneman84** [nathantannar4/InputBarAccessoryView#238]
I just updated to MessageKit 4.0. My chats are shown on a pagesheet VC. When the keyboard shows on iPad the input bar goes up way too much. This is on an iOS 16.0 simulator:

![Simulator Screen Shot - iPad Air (5th generation) - 2022-09-30 at 12 37 09](https://user-images.githubusercontent.com/9085167/193253907-9716e8d0-47fa-4304-bdf6-3d605bbcba38.png)

It used to work fine on older versions.

**Comment by Kaspik** [comment]
Hey.

1) Should this be MessageKit issue instead of IBAV?
2) There was a change in 6.1.0 that added bottom constraint - https://github.com/nathantannar4/InputBarAccessoryView/pull/230 - did you check that?

**Comment by nathantannar4** [comment]
Possibly related to #141, but could also be MessageKit

**Comment by Janneman84** [comment]
I managed to fix the issue myself. It turns out the fault lies with InputBarAccessoryView and not MessageKit.

The current code assumes the bar is positioned to the very bottom of the screen. In case of pagesheets on iPad this is not the case. Also when using VC containers this might happen. When the keyboard goes up the bar goes up the same amount even when it wasn't stuck to the bottom of the screen, causing a gap.

I created some code that checks and compensates for this. I'm tweaking it right now.

**Comment by nathantannar4** [comment]
@Janneman84 thanks for finding the fault. I haven't been working on this project, though I'm trying to get involved again. 

It's seems as though there have been some regressions perhaps in recent released of InputBarAccessoryView? Must be the case if you updated and it broke.

**Comment by Janneman84** [comment]
I believe it recently moved from being an `inputAccessoryView` to being a regular subview. I don't know why this was done, but I'm glad they did because it fixes some weird bugs and glitches.

This move caused new bugs of course, but nothing that can't be fixed.

**Comment by Kaspik** [comment]
Yes, this was done in https://github.com/MessageKit/MessageKit/pull/1704.

**Comment by Janneman84** [comment]
Oh I see so this package supports both ways and you can choose?

**Comment by Janneman84** [comment]
I created some code to fix the issue. I'm sorry it's not a proper MR but it's a bit hacky so if someone can give it a try first would be nice.

Try putting this in `KeyboardManager.swift`:
```swift
/// Used to fix a glitch that would otherwise occur when using pagesheets on iPad in iOS 14
private var justDidWillHide = false
```

```swift
/// When e.g. using pagesheets on iPad the inputAccessoryView is not stuck to the bottom of the screen.
/// This value represents the size of the gap between the bottom of the screen and the bottom of the inputAccessoryView.
private var bottomGap: CGFloat {
    if let inputAccessoryView = inputAccessoryView, let window = inputAccessoryView.window, let superView = inputAccessoryView.superview {
        return window.frame.height - superView.convert(superView.frame, to: window).maxY
    }
    return 0
}
```

Change this:
```swift
var yCoordinateDirectlyAboveKeyboard = -frame.height
```
To this:
```swift
var yCoordinateDirectlyAboveKeyboard = -frame.height + bottomGap
```

And most importantly replace the `bind` method like this:
```swift
@discardableResult
open func bind(inputAccessoryView: UIView, withAdditionalBottomSpace additionalBottomSpace: (() -> CGFloat)? = .none) -> Self {

    guard let superview = inputAccessoryView.superview else {
        fatalError("`inputAccessoryView` must have a superview")
    }
    self.inputAccessoryView = inputAccessoryView
    self.additionalBottomSpace = additionalBottomSpace
    inputAccessoryView.translatesAutoresizingMaskIntoConstraints = false
    constraints = NSLayoutConstraintSet(
        bottom: inputAccessoryView.bottomAnchor.constraint(equalTo: superview.bottomAnchor, constant: additionalInputViewBottomConstraintConstant()),
        left: inputAccessoryView.leftAnchor.constraint(equalTo: superview.leftAnchor),
        right: inputAccessoryView.rightAnchor.constraint(equalTo: superview.rightAnchor)
    ).activate()

    callbacks[.willShow] = { [weak self] (notification) in
        guard
            self?.isKeyboardHidden == false,
            self?.constraints?.bottom?.constant == self?.additionalInputViewBottomConstraintConstant(),
            notification.isForCurrentApp
        else { return }

        let keyboardHeight = notification.endFrame.height
        self?.animateAlongside(notification) {
            self?.constraints?.bottom?.constant = min(0, -keyboardHeight + (self?.bottomGap ?? 0)) - (additionalBottomSpace?() ?? 0)
            self?.inputAccessoryView?.superview?.layoutIfNeeded()
        }
        
        // Doing it a second time delayed is required for accurate placement
        DispatchQueue.main.async {
            let bottomGap = self?.bottomGap ?? 0
            if bottomGap != 0 {
                self?.animateAlongside(notification) {
                    self?.constraints?.bottom?.constant = min(0, -keyboardHeight + bottomGap) - (additionalBottomSpace?() ?? 0)
                    self?.inputAccessoryView?.superview?.layoutIfNeeded()
                }
            }
        }
    }
    callbacks[.willChangeFrame] = { [weak self] (notification) in
        let keyboardHeight = notification.endFrame.height
        guard
            self?.isKeyboardHidden == false,
            notification.isForCurrentApp
        else {
            return
        }
        self?.animateAlongside(notification) {
            self?.constraints?.bottom?.constant = min(0, -keyboardHeight + (self?.bottomGap ?? 0)) - (additionalBottomSpace?() ?? 0)
            self?.inputAccessoryView?.superview?.layoutIfNeeded()
        }
        
        // Doing it a second time delayed is required for accurate placement
        DispatchQueue.main.async {
            let bottomGap = self?.bottomGap ?? 0
            if bottomGap != 0 && !(self?.justDidWillHide ?? false) {
                self?.animateAlongside(notification) {
                    self?.constraints?.bottom?.constant = min(0, -keyboardHeight + bottomGap) - (additionalBottomSpace?() ?? 0)
                    self?.inputAccessoryView?.superview?.layoutIfNeeded()
                }
            }
        }
    }
    callbacks[.willHide] = { [weak self] (notification) in
        guard notification.isForCurrentApp else { return }
        self?.justDidWillHide = true
        self?.animateAlongside(notification) { [weak self] in
            self?.constraints?.bottom?.constant = self?.additionalInputViewBottomConstraintConstant() ?? 0
            self?.inputAccessoryView?.superview?.layoutIfNeeded()
        }
        
        // Doing it a second time delayed is required for accurate placement
        DispatchQueue.main.async {
            self?.justDidWillHide = false
            self?.animateAlongside(notification) { [weak self] in
                self?.constraints?.bottom?.constant = self?.additionalInputViewBottomConstraintConstant() ?? 0
                self?.inputAccessoryView?.superview?.layoutIfNeeded()
            }
        }
    }
    return self
}
```

**Comment by fhernandezKt88** [comment]
I'm having big problems for this issue. How I can fix this if no configuration or something to disable this behavior at all ?. Please this component is heavily used by the community so try to fix this in a nice way. This is for the moment the unique problem I have with MessageKit/MessageInputBar !

**Comment by Janneman84** [comment]
Have you tried the code changes I suggested?

**Comment by fhernandezKt88** [comment]
> Have you tried the code changes I suggested?

I don't, because I can't touch KeyboardManager (I install this with SPM) so I can't. You don't have any other idea or solution here ? Thanks for the response.

**Comment by Janneman84** [comment]
You can check out the repo then add it to your Xcode project as a local package. It will conveniently override the SPM one. Then you'll be able to make changes.

I also just added a pull request.

**Comment by fhernandezKt88** [comment]
> You can check out the repo then add it to your Xcode project as a local package. It will conveniently override the SPM one. Then you'll be able to make changes.
> 
> I also just added a pull request.

i think is best to fix the problem in the main package for all others. Thanks a loot for the pr. @nathantannar4 please can u merge this pr?

**Comment by Kaspik** [comment]
We can just go and "merge it", but I did review it and requested some changes for simplification. Once it looks good, we will merge it.

**Comment by fhernandezKt88** [comment]
> We can just go and "merge it", but I did review it and requested some changes for simplification. Once it looks good, we will merge it.

Thanks you @Kaspik !

**Comment by fhernandezKt88** [comment]
@nathantannar4 @Kaspik some advance on this ?

**Comment by nathantannar4** [comment]
For some context I've been away from this project. Id like to get back and do some cleanup. I started using this project in an app and noticed some issues. I think along the way some bad changes were merged leading to this issue, since it was a regression from earlier versions.

**Comment by fhernandezKt88** [comment]
@Kaspik this is merged, thanks but, is the package updated ?

**Comment by Kaspik** [comment]
No, not yet. You can point SPM to the commit or branch.

**Comment by fhernandezKt88** [comment]
> No, not yet. You can point SPM to the commit or branch.

Yes, thanks.

**Comment by fhernandezKt88** [comment]
Working fine, tested in iPhone 13 Pro (real device) with iOS 16.2. Nice work guys !

**Comment by fhernandezKt88** [comment]
@Kaspik @nathantannar4 can this be updated with a new tag (6.2.3 for example) to be able to install the package without point to some branch or commit ?. Are something blocking this ?

**Comment by Kaspik** [comment]
I'll ship one later today / this week, sorry.

**Comment by ctlamy** [comment]
> No, not yet. You can point SPM to the commit or branch.

@Janneman84 
I tried installing commit 6d2f24396fd86924d5fe2fed7cfda4f9e932c363, for me InputBar initializes in incorrect position high up on screen but after you try and scroll it snaps down in correct position on top of keyboard.

Testing with MessageKit on iPhone14 Pro Max and also does on Simulator.

Am I using wrong branch?

https://github.com/nathantannar4/InputBarAccessoryView/assets/23286437/d3c39f2b-5c87-4cf2-84ea-259b908b57cb

**Comment by Janneman84** [comment]
Is this on iOS 17 perhaps?

**Comment by ctlamy** [comment]
> Is this on iOS 17 perhaps? Haven't tested that yet.

Ios 16.5.1

**Comment by Janneman84** [comment]
Does checking out the master branche work? It works fine in my own app and the MessageKit example app.

Does it work right on pagesheets on iPad? If not you might just be on a wrong version somehow.

**Comment by ctlamy** [comment]
Same behavior with master branch. 

But if I combine master branch with the hack from https://github.com/MessageKit/MessageKit/issues/1734#issuecomment-1221426408 ("`.ignoresSafeArea(.keyboard, edges: .bottom)` on the SwiftUI side") then its effective. Oh well I guess.

@fhernandezKt88 you got it resolved on its own?

**Comment by Janneman84** [comment]
You never mentioned you were using SwiftUI...

I tried the SwiftUI example and I get the issue too, but it was also broken without my fixes.

You're right that combining my fix with the `.ignoresSafeArea` thingy makes it work correctly again.

The made changes to the example app, maybe I'll make a PR.

**Comment by fhernandezKt88** [comment]
@ctlamy I'm using UIkit and this is solved with the PR: https://github.com/nathantannar4/InputBarAccessoryView/pull/244
