### ISSUE TITLE
SwiftUI Example Text Field too high, BottomStack too big

### ISSUE THREAD

**Issue by David77030** [nathantannar4/InputBarAccessoryView#239]
SwiftUI Example, no code change, found the input field too high by default, added color, found the bottom stack too high for unknown reason.  Anyone has fix to this ?

![Image 11-13-22 at 8 05 AM](https://user-images.githubusercontent.com/56947491/201525985-19eabd79-6667-4e5f-a665-ec82916e914e.jpg)

**Comment by David77030** [comment]
Closed

**Comment by itsfaraaz** [comment]
Was there any resolution to this @David77030
