### ISSUE TITLE
When i want to test the example :/

### ISSUE THREAD

**Issue by JulienLevallois** [nathantannar4/InputBarAccessoryView#24]
![image](https://user-images.githubusercontent.com/5727223/41062324-7ecd9040-69a3-11e8-8328-61e26d3889cf.png)

**Comment by nathantannar4** [comment]
Compact map was added in Swift 4.1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
If your playing around with the master branch there are changes planned for 2.0, i would checkout the 1.5.4 tag

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
