### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by yasiraliraj** [nathantannar4/InputBarAccessoryView#256]
Hello Input Bar Accessory View Team,

I hope this message finds you well. I would like to draw your attention to an important update required by the App Store. Starting May 1, 2024, a privacy manifest will be mandatory for all apps. Given the ongoing development and support for your SDK, integrating this feature would be highly beneficial for ensuring compliance with the new App Store guidelines. This addition would greatly help developers like us in continuing to provide seamless services through our applications. We appreciate your attention to this matter and look forward to any updates you can provide.

Thank you for your continued support.

**Comment by Kaspik** [comment]
I'm not aware of IBAV using anything mentioned / required by Apple? :)

**Comment by nathantannar4** [comment]
Yes this is not applicable to IBAV. This is just a UIKit based framework.
