### ISSUE TITLE
About paste monitoring

### ISSUE THREAD

**Issue by rays77** [nathantannar4/InputBarAccessoryView#257]
I want to check whether certain data has been copied when pasting, and then the corresponding pop-up window will pop up. How should I deal with it? Please help me, thank you! ! !

**Comment by rays77** [comment]
![image](https://github.com/nathantannar4/InputBarAccessoryView/assets/6637723/5334fb44-0772-4040-840c-8185b8dab0d5)
These two methods are already handled internally, how do I handle these events outside?

**Comment by nathantannar4** [comment]
You would probably need to subclass the InputTextView. You could then subclass InputBarAccessoryView, and set your new InputTextView via the setMiddleContent API

**Comment by rays77** [comment]
thank you verry mach!
