### ISSUE TITLE
Why AttachmentManager extensions methods are 'finals'?

### ISSUE THREAD

**Issue by Coriolan-Bataille** [nathantannar4/InputBarAccessoryView#258]
Was running version  '5.4.0' via cocoapods, so could edit cellForItemAt to 'open' instead of 'final'
Now running  '6.3.0' via SPM and can't to this edit anymore.

I'm overriding cellForItemAt, but can't anymore.
I would like to understand the reason behind it.

```
import UIKit
import InputBarAccessoryView

class CustomAttachmentManager: AttachmentManager {
    
    override var tintColor : UIColor {
        return .black
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        if indexPath.row == attachments.count && showAddAttachmentCell {
            return createCustomAttachmentCell(in: collectionView, at: indexPath)
        }
        //[...]
    }

   //[...]
}
```

Xcode error:
```
Instance method overrides a 'final' instance method
Overriding non-open instance method outside of its defining module
```

I believe in older versions of InputBarAccessoryView, AttachmentManager extension were not in final if my memory is correct.

Thank you for the time spend reading my questions, 
and thx for sharing with us that great project.
Best Regards Cory.

**Comment by Kaspik** [comment]
I believe you have to conform to the delegate methods itself, not _just_ override the conformance from superclass.
Try adding `extension CustomAttachmentManager: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {` to your code and handling all the code in collection view by yourself?

**Comment by Coriolan-Bataille** [comment]
That was a lighting fast answer.
Thank you for the suggestion.
I will explore that direction.
(And yes using it since a very long time haha so I was a bit outdated) 🤭
