### ISSUE TITLE
Offset Position for TabBarController

### ISSUE THREAD

**Issue by bribar** [nathantannar4/InputBarAccessoryView#26]
InputBarAccessoryView covers tabBarController. I didn't see a setting to offset the `backgroundView`. Is this possible? Much of the methods or properties like `backgroundViewBottomAnchor` are private.

I tried resetting some anchors but didn't take effect.

Thanks!

**Comment by nathantannar4** [comment]
No this cannot be done. It is an InputAccessoryView thus will always be held at the bottom of the screen. Moreover, it is considered bad UX practice to put an input bar over a tab bar, you should use the InputBarAccessoryView on a screen that doesn't have a tabbar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bribar** [comment]
Interesting. Ok Thanks!

**Comment by Alexookah** [comment]
@bribar i am using a global chat with tabBar. Any chance adding an option for a bottom Offset?

**Comment by Dreamer4ik** [comment]
> @bribar i am using a global chat with tabBar. Any chance adding an option for a bottom Offset?

Did you find solution ?

**Comment by bribar** [comment]
@Dreamer4ik I canned it and implemented a custom solution. This was a deal breaker at the time for the project I was working on.

**Comment by JWAutumn** [comment]
@Dreamer4ik @bribar 
I am also facing a similar issue, and the solution I used is:
```
func onReceived(notification: Notification) {
    switch notification.name {
    case UIApplication.keyboardWillHideNotification:
        UIView.animate(withDuration: 0.25) {
            self.conversationController.messageInputBar.middleContentViewPadding.bottom = .zero
        }
    case UIApplication.keyboardWillShowNotification:
        UIView.animate(withDuration: 0.25) {
            self.conversationController.messageInputBar.middleContentViewPadding.bottom = Device.Dimensions.TabBarHeight
        }
    default:
        ()
    }
}
```
Manually set the middleContentViewPadding.bottom to the height of the TabBar when the keyboard hide or show.
Don't forget about the safe area....
