### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by brod-ie** [nathantannar4/InputBarAccessoryView#28]
I've reversed the stack views to provide a RTL layout with the send button on the left and input on the right. Unfortunately the placeholder's constraints means it stays on the left of this input bar regardless of the underlying text views alignment:
![simulator screen shot - iphone x - 2018-07-10 at 09 05 14](https://user-images.githubusercontent.com/1520630/42497276-be4adc40-8420-11e8-80de-27a7007164b5.png)
[These are the programmatic constraints related to the UILabel](https://github.com/nathantannar4/InputBarAccessoryView/blob/6e553318412f14fd61d8e504a398cc38381804be/InputBarAccessoryView/Views/InputTextView.swift#L177-L191) acting as the placeholder, from what I can gather this is referencing the left and right anchors of the parent, aka UITextView. For this reason I'm confused to why the UILabel isn't the full width of the UITextView?

If this were the case I could easily set the text alignment property on the placeholder to achieve the RTL effect.

**Comment by nathantannar4** [comment]
Thanks for bringing this to my attention, I have updated it to support RTL in version 2.2.1, please let me know if this fixes your problem!

**Comment by brod-ie** [comment]
You da man @nathantannar4! Sweet I'll get this in our next build and keep you posted 😀

**Comment by brod-ie** [comment]
@nathantannar4 👏 👏 👏 Works great, too bad I can't speak Arabic!

![simulator screen shot - iphone x - 2018-07-24 at 10 34 02](https://user-images.githubusercontent.com/1520630/43129950-6c6fdaac-8f2d-11e8-9414-30f87a9dd608.png)

**Comment by nalhamad** [comment]
@nathantannar4 thanks for the help with RTL support, actually I'm facing the same issue in version 4.3.1. text alignment works probably unlike the place holder.

![Simulator Screen Shot - iPhone 11 - 2019-12-04 at 18 59 49](https://user-images.githubusercontent.com/57365810/70158525-7165f900-16c8-11ea-8dac-8dd0e564c72a.png)
![Simulator Screen Shot - iPhone 11 - 2019-12-04 at 19 00 11](https://user-images.githubusercontent.com/57365810/70158526-71fe8f80-16c8-11ea-80c0-ff72ef46c1f1.png)
