### ISSUE TITLE
endEditing not working

### ISSUE THREAD

**Issue by MotoxX** [nathantannar4/InputBarAccessoryView#29]
For usablity puposes I want the keyboard to disappear before the message is acutally send on pressing a button.

So I tried to use 

- inputBar.endEditing(true)
- inputBar.inputTextView.endEditing(true)
- self.view.endEditing(true)

But they are all not working. The inputBar stays active and the keyboard doesn't hide.
Any idea?

**Comment by nathantannar4** [comment]
The input bar is an InputAccessoryView, which means it's visible when the UIViewController is the first responder. You need to `resignFirstResponder` on it. End editing will have no effect. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MotoxX** [comment]
inputBar.inputTextView.resignFirstResponder() solved the problem! Thanks for your quick help! By the way, this git is great!
