### ISSUE TITLE
KeyboardManager doesn't seem to handle bottom UITabBar

### ISSUE THREAD

**Issue by BabyAzerty** [nathantannar4/InputBarAccessoryView#30]
My app has a bottom UITabBarController.tabBar and I believe that the KeyboardManager doesn't handle it out of the box.

The InputBar has a red background color.

I'm using the code from the "Example" folder.

Initial state:

![image](https://user-images.githubusercontent.com/1152371/44347073-49349580-a497-11e8-9e9a-021286088745.png)

When opening the keyboard state, there is a white padding that I suspect coming from the UITabBar:

![image](https://user-images.githubusercontent.com/1152371/44347112-505ba380-a497-11e8-9ab4-2409150aa3e1.png)

EDIT: I found out that trying to pass a potentiel uitabbar in `@discardableResult open func bind(inputAccessoryView: UIView, usingTabBar tabBar: UITabBar? = nil) -> Self` does fix the problem as so:

```swift
    let tabBarHeight = tabBar?.bounds.size.height ?? 0
    callbacks[.willShow] = { [weak self] (notification) in
        let keyboardHeight = notification.endFrame.height
        guard
            self?.isKeyboardHidden == false,
            self?.constraints?.bottom?.constant == 0,
            notification.isForCurrentApp else { return }
        self?.animateAlongside(notification) {
            self?.constraints?.bottom?.constant = -keyboardHeight + tabBarHeight
            self?.inputAccessoryView?.superview?.layoutIfNeeded()
        }
    }
    callbacks[.willChangeFrame] = { [weak self] (notification) in
        let keyboardHeight = notification.endFrame.height
        guard
            self?.isKeyboardHidden == false,
            notification.isForCurrentApp else { return }
        self?.animateAlongside(notification) {
            self?.constraints?.bottom?.constant = -keyboardHeight + tabBarHeight
            self?.inputAccessoryView?.superview?.layoutIfNeeded()
        }
    }
```

**Comment by nathantannar4** [comment]
Hi @BabyAzerty . KeyboardManager mimics having a view anchored to the bottom so you would need to implement the callbacks yourself. Generally, it's recommended that user interfaces avoid having the  bar on top of a tab bar. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
You would have to implement the constraints yourself. The private ones are for default use
