### ISSUE TITLE
Another text field with an input accessory view possible?

### ISSUE THREAD

**Issue by hipwelljo** [nathantannar4/InputBarAccessoryView#39]
This may be an interesting question. 

I have a scenario in my app where I need a view controller to have a text view in an `inputAccessoryView` and a text field at the top. This works great, when both become first responder the bottom input bar is always above the keyboard as desired. But it gets interesting when I assign an `inputAccessoryView` to the top text field. This causes the input bar to drop down to the bottom underneath the keyboard and only that text field's input accessory view is visible. I actually need both to be visible. It sounds strange, but the top text field's input accessory view blends right into the keyboard, so it would appear as part of the keyboard with a single input accessory view even though it's actually two stacked views. Do you see any way to do that?

Looks like it might work with the subview approach instead but this isn't really acceptable because when you drag down on the keyboard the input bar sluggishly responds.

**Comment by nathantannar4** [comment]
@hipwelljo I'm having trouble understanding the layout your explaining. Do you have a sketch or wireframe to could share?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hipwelljo** [comment]
Sure thing :)
<img width="919" alt="screen shot 2018-09-29 at 7 13 17 pm" src="https://user-images.githubusercontent.com/6282848/46251865-59d41600-c41c-11e8-8d2e-919d1ae62cdd.png">

**Comment by nathantannar4** [comment]
@hipwelljo is the issue that the InputAccessoryView disappears when the top text field becomes the first responder? You could override the `canResignFirstResponder: Bool` property of the `UIViewController`

https://developer.apple.com/documentation/uikit/uiresponder/1621097-resignfirstresponder

**InputBarAccessoryView** is designed to be an `InputAccessoryView` for a `UIViewController`. I cannot guarantee functionality for using it as an `InputAccessoryView` for something like a `UITextField`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hipwelljo** [comment]
Yes that is the issue. So interestingly, overriding `canResignFirstResponder` to return `false` prevents it from presenting the keyboard when you tap the text view. I do want to allow it to resign first responder though.

Note that I'm not assigning the InputBarAccessoryView as the top text field's `inputAccessoryView` - only for the view controller as it was intended.

**Comment by nathantannar4** [comment]
@hipwelljo You can't have two `inputAccessoryView` visible at the same time. An `inputAccessoryView` is tied to the `UIWindow` and there can only be one. You can't have 2 first responders. Either the `UIViewController` is the first responder or the `UITextField`

**Comment by hipwelljo** [comment]
Ok, makes sense. It seems this type of interface isn't reallllly achievable then, at least not with the nice responsive interactive keyboard dismissal.
