### ISSUE TITLE
How to add a custom separator at top?

### ISSUE THREAD

**Issue by loverde-co** [nathantannar4/InputBarAccessoryView#40]
Hi @nathantannar4 , thanks for this project!
So, i need to customize the top separator ( i can hide the default ). But how to add an UIView at top ( UIStack top ).  There is a way ? Reeded all README file and GET START too.
Thanks!

**Comment by nathantannar4** [comment]
Hi @loverde-co ,

Im not sure what you quite mean by customizing the top separator. 

As for accessing the top Stack view, all stack views are open so you can call `.addArrangedSubview` on whichever you would like.  

Alternatively if the view you are adding conforms to `InputItem` you can use the `.setStackViewItems` API

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by loverde-co** [comment]
Hi @nathantannar4 , I tried this with the stack top. But the separator I wanted was too big because the size is intrinsicContentSize, so I used the separator and I changed the color to white and I add shadow to it and take advantage of the effects I need. Small shade and thinner separator. Thanks for the ASP reply!
