### ISSUE TITLE
don`t add prefix on autocomplete

### ISSUE THREAD

**Issue by syrakozz** [nathantannar4/InputBarAccessoryView#44]
hi , 
i dont want to append the prefix to the autocomplete how i can accomplish that like 

[img]    mail@example.com

not 

[img]     @mail@.example.com

**Comment by nathantannar4** [comment]
Try setting `keepPrefixOnCompletion` to false

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
You can customize the cell that's returned be anything you want. It's apart of the dataSoure methods. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
