### ISSUE TITLE
Examples don't set UITableView bottom inset properly

### ISSUE THREAD

**Issue by jameshays** [nathantannar4/InputBarAccessoryView#47]
When viewing the Examples on iPhone X, the UITableView bottom inset is not set correctly.  There's no way to scroll to the bottom of the table.  This is with release 4.2.0

**Comment by nathantannar4** [comment]
This is just the example, it doesn't effect the library. InputBarAccessoryView is perfectly safe to use with an iPhone X, you just need to allocate the appropriate inset when the size changes depending on how your scroll view is positioned in the frame of the UIViewController

**Comment by jameshays** [comment]
Are you certain?  This seems to be an issue with binding the scroll view, which is framework code.

**Comment by nathantannar4** [comment]
@jameshays Binding the scroll view? Not sure what you mean by this. This library doesn't automatically manage the scrollview insets.

**Comment by jameshays** [comment]
Sorry, disregard.  I was thinking about this:
`open func bind(to scrollView: UIScrollView) -> Self`

but reading this:
`open func bind(inputAccessoryView: UIView) -> Self`

Anyway, I have my issue resolved.
