### ISSUE TITLE
Content offset problem

### ISSUE THREAD

**Issue by waltcow** [nathantannar4/InputBarAccessoryView#52]
Hi @nathantannar4

The content offset is wrong when user enter the scrollable view,  the bottom item is unreadable though user scroll to the bottom.  But when user tap the input text field,  keyboard show,  the bottom item can be seen again

![image](https://user-images.githubusercontent.com/3941174/51103644-84f14280-181e-11e9-8dbb-be3ae4b32566.png)

![image](https://user-images.githubusercontent.com/3941174/51103742-d39edc80-181e-11e9-8c47-3a2ae6caaeb0.png)

**Comment by nathantannar4** [comment]
@waltcow found the issue in the example, was toggling the `InputTextView` `isUserInteractionEnabled` and that must throw off something with UIKits auto layout? Not sure. After removing those lines I don't see the extra inset. I updated the Example

**Comment by waltcow** [comment]
@nathantannar4 Thanks.

I just find another issue with **KeyboardManager**，after the keyboard is dismissed,  the **didHide** registered callback is never called.

**Comment by nathantannar4** [comment]
Have you asigned a callback for didHide? There isn't one by default. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
