### ISSUE TITLE
How to Attach send button to bottom of the Input TextView

### ISSUE THREAD

**Issue by ajjumehra** [nathantannar4/InputBarAccessoryView#53]

**Comment by nathantannar4** [comment]
You can use the bottom stack view! 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leacode** [comment]
first hide the original send button:
`
messageInputBar.setRightStackViewWidthConstant(to: 0, animated: false)
`

then define your own send button:
`
let bottomSendButton: InputBarSendButton = {
        return InputBarSendButton()
            .configure {
                $0.setSize(CGSize(width: 52, height: 36), animated: false)
                $0.isEnabled = false
                $0.title = "Send"
                $0.titleLabel?.font = UIFont.systemFont(ofSize: 15, weight: .bold)
            }.onTouchUpInside {
                $0.inputBarAccessoryView?.didSelectSendButton()
        }
    }()
`
 This can be the same code as the code in source code, it will act the same way.

Finally put it in the bottom stack view:
`
let functionItems = [ .flexibleSpace, bottomSendButton]
messageInputBar.setStackViewItems(functionItems, forStack: .bottom, animated: false)
`
