### ISSUE TITLE
InputBar hides bottom part of tableview

### ISSUE THREAD

**Issue by EgorkZe** [nathantannar4/InputBarAccessoryView#54]
Hello! I found inputbar overlays tableview in bottom part in collapsed state. How can I fix it? 
<img width="414" alt="screenshot 2019-02-05 at 16 15 11" src="https://user-images.githubusercontent.com/4862279/52275898-dc885700-2961-11e9-8948-8b9c79532e89.png">

**Comment by nathantannar4** [comment]
You should be using the delegate method of the input bar size changes to adjust the bottom inset of your collection view or tableview
