### ISSUE TITLE
Is it possible to prevent InputBar from move up when show keyboard ? 

### ISSUE THREAD

**Issue by es0o** [nathantannar4/InputBarAccessoryView#55]

**Comment by nathantannar4** [comment]
To clarify, you want the keyboard to cover the input bar?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by es0o** [comment]
No, I want to use this pod (or only TextView without buttons) at the Top of the Screen.
![05- Post Page - Add Comment (Light Version) English](https://user-images.githubusercontent.com/16314212/54487667-6ef51200-48a1-11e9-85ba-918e8f51fa1c.png)

**Comment by nathantannar4** [comment]
If you just want the text view you can create an instance of it and add it to the view. It's an `InputTextView`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by es0o** [comment]
ok, I want to show mention list when typing "@" ... so I have to user autocompleteManager with InputTextView ==> but while typing textView can't call

**Comment by nathantannar4** [comment]
That is very different that the original question you posed. In short, the autocomplete manager requires the delegate. If you need to add some functionality I suggest using `NotificationCenter` or subclass and add logic 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
