### ISSUE TITLE
Unable to remove white background.

### ISSUE THREAD

**Issue by farhanmirza27** [nathantannar4/InputBarAccessoryView#56]
![IMG_6554](https://user-images.githubusercontent.com/44664906/55054709-90fd4a00-5082-11e9-8852-40562bd980ae.jpg)

Unable to remove this white background. tried everything. Please guide me

**Comment by nathantannar4** [comment]
Have you tried the `backgroundView` or `contentView`? It's easier for to help others if you list what you have done rather. Also, you could use the visual debugger to get the view hierarchy to see which view exactly you want to modify

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by farhanmirza27** [comment]
I have used your example for iMessage 

This class


class chatInputBar: InputBarAccessoryView {
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        configure()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func configure() {
        inputTextView.backgroundColor = .white
        inputTextView.placeholderTextColor = UIColor(red: 0.6, green: 0.6, blue: 0.6, alpha: 1)
        inputTextView.textContainerInset = UIEdgeInsets(top: 8, left: 16, bottom: 8, right: 36)
        inputTextView.placeholderLabelInsets = UIEdgeInsets(top: 8, left: 20, bottom: 8, right: 36)
        inputTextView.layer.borderColor = UIColor(red: 200/255, green: 200/255, blue: 200/255, alpha: 1).cgColor
        inputTextView.layer.borderWidth = 1.0
        inputTextView.layer.cornerRadius = 16.0
        inputTextView.layer.masksToBounds = true
        inputTextView.scrollIndicatorInsets = UIEdgeInsets(top: 8, left: 0, bottom: 8, right: 0)
        setRightStackViewWidthConstant(to: 38, animated: false)
        setStackViewItems([sendButton, InputBarButtonItem.fixedSpace(2)], forStack: .right, animated: false)
        sendButton.imageView?.backgroundColor = tintColor
        sendButton.contentEdgeInsets = UIEdgeInsets(top: 2, left: 2, bottom: 2, right: 2)
        sendButton.setSize(CGSize(width: 36, height: 36), animated: false)
        sendButton.image = UIImage(named: "arrow_right_iPhone")
        sendButton.title = nil
        sendButton.imageView?.layer.cornerRadius = 16
        sendButton.backgroundColor = .clear
        middleContentViewPadding.right = -38
        separatorLine.isHidden = true
        isTranslucent = false
    }
    
}


So where I am using instance of this class I tried to use clear its background color. its not working

**Comment by nathantannar4** [comment]
You didn't try the views I just mentioned.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by farhanmirza27** [comment]
Resolved. Thanks

**Comment by fukemy** [comment]
@farhanmirza27 how did u solved this? I need to set transparent background, thanks in advance
