### ISSUE TITLE
CocoaPod could not find version 4.2.2

### ISSUE THREAD

**Issue by escapeanaemia** [nathantannar4/InputBarAccessoryView#57]
Hello, Thanks for your Awesome library :)
I tried to install InputBarAccessoryView with pod, but some error I found
```
CocoaPods could not find compatible versions for pod "InputBarAccessoryView":
  In Podfile:
    InputBarAccessoryView (= 4.2.2)
```
so I do it with 4.2.1 and It works well.

**Comment by escapeanaemia** [comment]
I solved it myself.... my pod was problem 
```
pod repo update
```
I'm so sorry for spam issue 😢

**Comment by danhhgl** [comment]
I got this issue. Thank you for your question and answer! :)
