### ISSUE TITLE
Press and hold mic button

### ISSUE THREAD

**Issue by rogeriowiethornjr** [nathantannar4/InputBarAccessoryView#59]
How can I create a press and hold button to record and send audio. I'm using MessageKit.

**Comment by nathantannar4** [comment]
That is a loaded question, what have you tried so far? How do you think you would implement it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by harshhb** [comment]
@rogeriowiethornjr were you able to get this done?

**Comment by leacode** [comment]
You can set a button on the middle view:
```
lazy var recordButton: UIButton = {
        let button = UIButton()
        button.layer.cornerRadius = 8
        button.backgroundColor = .chatRecordButtonBgColor
        button.setTitle("press to record audio", for: .normal)
        button.titleLabel?.font = UIFont.boldSystemFont(ofSize: 17.0)
        button.setTitleColor(.chatTextViewTintColor, for: .normal)
        return button
    }()
```

Then:
```
messageInputBar.setMiddleContentView(recordButton, animated: false)
```

Add long press gesture or whatever you want to `recordButton` to record audio.

**Comment by harshhb** [comment]
Thanks @leacode. Managed to get it done.

**Comment by rogeriowiethornjr** [comment]
Thank you @leacode! I'll try it. 
My best regards

**Comment by HagerGamal95** [comment]
![Simulator Screen Shot - iPhone XR - 2019-05-26 at 12 17 45](https://user-images.githubusercontent.com/36477659/58380349-49c30500-7fb0-11e9-912b-c881823e938a.png)
@leacode  
this worked for me but I need to make the record button n smaller size beside the send button and keep the text field like this image 
![Screen Shot 2019-05-26 at 12 19 40 PM](https://user-images.githubusercontent.com/36477659/58380399-e1285800-7fb0-11e9-8ec9-d8fcbbe7b7f4.png)
this can be applied or not with this pod ??

**Comment by leacode** [comment]
@HagerGamal95 

Yes, you can put items in rightStackView. Just like the send button does.
```
let items = [recordButton, sendButton]
messageInputBar.setStackViewItems([items], forStack: .right, animated: false)
```

**Comment by nathantannar4** [comment]
@leacode is correct. Dont forget to adjust the allowable right stack view width with `setRightStackViewWidthConstraint`

Also to add to @leacode do not animate item change if you are doing so in viewDidLoad
