### ISSUE TITLE
Pod install issue

### ISSUE THREAD

**Issue by mohsinalimat** [nathantannar4/InputBarAccessoryView#6]
Hello,

[!] Unable to find a specification for `InputBarAccessoryView`

**Comment by nathantannar4** [comment]
I suppose that there is a problem with your pod master repo because this is a new Pod. Delete it and download it again.

You can do:

```
pod repo remove master
pod setup
pod install
```

Or:

```
sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod install
```

**Comment by mohsinalimat** [comment]
But i am installing another pod

**Comment by nathantannar4** [comment]
`pod install` will fail if your own master repo does not include the latest specs. I cannot recreate the issue and have verified that `InputBarAccessoryView` is live. I believe the issue is centered around your own pods environment.

**Comment by mohsinalimat** [comment]
Ok thanks and let me try tomorrow :)

**Comment by Dreamer4ik** [comment]
I'm get a same problem how you fixed it ? 

I try add source 'https://github.com/CocoaPods/Specs.git' , but it's didn't help
