### ISSUE TITLE
Any way to add extra panel to the bottomStackView?

### ISSUE THREAD

**Issue by leacode** [nathantannar4/InputBarAccessoryView#60]
I try it this way: 
```
messageInputBar.bottomStackView.axis = .vertical
messageInputBar.bottomStackView.distribution = .fillProportionally
```
Then I add two stackViews to the  bottomStackView
```
messageInputBar.bottomStackView.addArrangedSubview(toolBarStackView)
messageInputBar.bottomStackView.addArrangedSubview(functionPanelStackView)
```

It only shows the first stackView which is toolBarStackView

What I want is to add a functionPanel below it so I can add extra content in it.

**Comment by nathantannar4** [comment]
Do you have items in your first and second stack views you added? If you set to fill proportionally it will determine a size based on the views intrinsic content size. So size constraints would have to be added to the the views you add to your new stack views. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leacode** [comment]
> Do you have items in your first and second stack views you added? If you set to fill proportionally it will determine a size based on the views intrinsic content size. So size constraints would have to be added to the the views you add to your new stack views.
> 
> Sent with [GitHawk](http://githawk.com)

You're right, I've changed the dictribution to .fill and add constraint to the view in the second stack view. It works.

```
functionPanelStackView.addArrangedSubview(functionView)
        
functionView.heightAnchor.constraint(equalToConstant: 100.0).isActive = true
functionView.widthAnchor.constraint(equalToConstant: UIScreen.main.bounds.size.width).isActive = true
```

Thank you.

**Comment by nathantannar4** [comment]
Np! By the way, you shouldn't need a width anchor. That code will break if you end up supporting landscape orientation

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leacode** [comment]
> Np! By the way, you shouldn't need a width anchor. That code will break if you end up supporting landscape orientation
> 
> Sent with [GitHawk](http://githawk.com)

The width will be 0 if I didn't set width anchor. This also cause constraint conflict. But it looks OK.

I'm still working on it. Any suggestion?

**Comment by leacode** [comment]
@nathantannar4 

Finally it works:

```
messageInputBar.bottomStackView.addArrangedSubview(toolBarStackView)
messageInputBar.bottomStackView.addArrangedSubview(functionPanelStackView)

// config toolbar
let toolBarItems = [voiceButton, faceButton, addButton, .flexibleSpace, bottomSendButton]
toolBarItems.forEach {
    $0.inputBarAccessoryView = messageInputBar
    $0.parentStackViewPosition = .top
    toolBarStackView.addArrangedSubview($0)
}

// config function panel
functionPanelStackView.addArrangedSubview(functionView)
functionView.heightAnchor.constraint(equalToConstant: 100.0).isActive = true
toolBarStackView.widthAnchor.constraint(equalTo: messageInputBar.bottomStackView.widthAnchor, multiplier: 1.0).isActive = true
functionPanelStackView.widthAnchor.constraint(equalTo: messageInputBar.bottomStackView.widthAnchor, multiplier: 1.0).isActive = true
```

The two stack views inside bottomStackView won't fill the width. So I add width constraints to them.
Now it's ok for me.
