### ISSUE TITLE
Cannot Run example project

### ISSUE THREAD

**Issue by gunwooKim-Korea** [nathantannar4/InputBarAccessoryView#61]
getting this error No such module 'InputBarAccessoryView'

there is no pod file in root of example folder

Also, this error occur

 directory not found for option '-F/Users/*/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphonesimulator/InputBarAccessoryView'

**Comment by nathantannar4** [comment]
Clean your build folder, delete your xcodes derived data and then rebuild. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gunwooKim-Korea** [comment]
it's not solved
Example occur No such module 'InputBarAccessoryView'
also my porject occur error No such module 'InputBarAccessoryView'

**Comment by nathantannar4** [comment]
@gunwooKim-Korea I'm sorry this is not something I can reproduce. It sounds like you didn't build the dependency `InputBarAccessoryView` correctly. Re-run `pod repo update master` then `pod install`. Or if you're using Carthage `carthage update InputBarAccessoryView --platform ios`

Make sure that you are using the correct library version based on your projects swift version

**Comment by kirti301290** [comment]
@nathantannar4 it give me same error as @gunwooKim-Korea 
there is no pod file in given example how can run pod  command
Thanks

**Comment by nathantannar4** [comment]
You don't need the Podfile I have it linked in my project settings

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kirti301290** [comment]
@nathantannar4  thank for reply but it not  working to me in Xcode10.2
i have fixed problem using created pod and added  pod

**Comment by whoyawn** [comment]
@kirti301290 @gunwooKim-Korea Run Open root workspace file, go to the schema drop-down in Xcode, then select Example. You shouldn't be opening the Example.xcodeproj.

**Comment by Kaspik** [comment]
Afaik there is no issue with running example project. Closing.
