### ISSUE TITLE
RxInputBarAccessoryViewDelegate

### ISSUE THREAD

**Issue by fmirault** [nathantannar4/InputBarAccessoryView#62]
Hi ! 

Thank you for this awesome library.
I'd like to use the Rx proxy, but it seems that this extension is not accessible (not public) so I cannot use it. I tried using inputBar.rx_delegate but this is not recognized.

Maybe this extension could also be used like other rx libraries, so renaming rx_delegate to rx only ?

Thank you :)

**Comment by nathantannar4** [comment]
@fmirault My apologies, I started working on Rx support but never fully tested it. I did forget to mark them as public.

Can you try setting your pod to pull from the master branch? I pushed some changes. Also please let me know if you think any other Rx proxies would be useful 😊

**Comment by nathantannar4** [comment]
Fixed in 4.3.1, please add `InputBarAccessoryView/RxExtensions` to your Podfile 😊
