### ISSUE TITLE
InputBar stack over keyboard

### ISSUE THREAD

**Issue by Jakkawad** [nathantannar4/InputBarAccessoryView#63]
I download example project and run it.
but when I switch app to Facebook message rand in Facebook messager app is active keyboard and I switch return to example app it happen

Device
- iPhone XS

** example subview style
![IMG_7345](https://user-images.githubusercontent.com/12533828/58635417-09e58000-8318-11e9-8b9c-99a07148ca34.PNG)

** and InputAccessView happen same subview but I animation down to correct positions like pull down to hide

thank you

**Comment by nathantannar4** [comment]
This is the default behaviour for how iOS manages things. You will notice that if you repeat your steps only switching to facebook messenger (or even iMessage, etc) the input bar on the other app is raised for a moment before dismissing.

**Comment by Jakkawad** [comment]
how to move inputBar to default like dismissing keyboard on KeyboardManager?

thank you

**Comment by nathantannar4** [comment]
@Jakkawad I'm not sure what your asking

**Comment by AbcTM** [comment]
I have the same problem

**Comment by nathantannar4** [comment]
This issue has become stale/outdated. Please re-open if desired.
