### ISSUE TITLE
Input Bar appear automatic when dismissal image

### ISSUE THREAD

**Issue by hhoangna** [nathantannar4/InputBarAccessoryView#64]
Sorry I not good at English
In Chat view controller, I present a ImageView that has dismissal.
When i just try dismiss and release, not dismiss completion. inputbar automatic appear.
Please help me to prevent inputbar appear
![ezgif com-optimize](https://user-images.githubusercontent.com/26923574/59319723-e944ff00-8cf5-11e9-9e1d-edc9721d8509.gif)

**Comment by nathantannar4** [comment]
It looks like an error in your view controller transition. Your image preview controller is dismissed and then your messages controller becomes the first responder so the input bar appears. You should only dismiss the image preview controller when the drag gesture on the image ends 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
How can I do like Messenger App? In Messenger, when I pan gesture on images, i still see input bar behind preview controller.

**Comment by nathantannar4** [comment]
Hmm, maybe try playing with the presentation style of the view controller to be `.overCurrentContext`? 

Or, rather than presenting a new controller just add the image as a subview. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
Thanks a lot. I had found a solution. It is a trick :)

**Comment by nathantannar4** [comment]
@hhoangna what did you find worked for you?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hassan31** [comment]
Hi, @hhoangna I just saw that you have added Emoji button inside the InputTextView, can you please let me know how can I add this to the InputBarView?

Thanks

**Comment by hhoangna** [comment]
@hassan31 I just calculate and constraint. 

Try this 
```
private func setupLeftInputBarItem() {
        setLeftStackViewWidthConstant(to: 40, animated: false)
        middleContentViewPadding.left = -34
        btEmotion = makeButton(named: "ic_sticker_gray", onSelected: "ic_sticker_colored", size: CGSize(width: 40, height: 40))
        btEmotion.contentEdgeInsets = UIEdgeInsets(top: 6, left: 16, bottom: 10, right: 0)
        btEmotion.tag = 21
        setStackViewItems([btEmotion], forStack: .left , animated: false)
        
        invalidateIntrinsicContentSize()
    }

private func makeButton(named: String, onSelected nameSelect:String, size: CGSize) -> InputBarButtonItem {
        return InputBarButtonItem()
            .configure {
                $0.spacing = .fixed(10)
                $0.setSize(size, animated: false)
                $0.image = UIImage(named: named)?.withRenderingMode(.alwaysOriginal)
                $0.tintColor = UIColor(white: 0.8, alpha: 1)
            }.onSelected {
                $0.tintColor = .vinTextColor
                $0.image = UIImage(named: nameSelect)?.withRenderingMode(.alwaysOriginal)
            }.onTouchUpInside { item in
                //print("Item Tapped: \(item.tag)")
                if(item.tag == 21){
                    self.keyboardType = self.keyboardType == .emoji ? .text : .emoji
                    self.showKeyBoard(type: self.keyboardType, animated: true)
                }
            }
    }
```

**Comment by hassan31** [comment]
@hhoangna Awesome, thanks alot, it works. :)
