### ISSUE TITLE
Send button text too long when internationalized

### ISSUE THREAD

**Issue by sarbogast** [nathantannar4/InputBarAccessoryView#68]
I'm trying to internationalize the text of the send button in InputBarAccessoryView in MessageKit. The text in French is a little longer than the text in English ("Envoyer" vs "Send") and the size of the button seems to be fixed. I tried the following code but it doesn't seem to work:

        messageInputBar.sendButton.configure {
            let font = UIFont.systemFont(ofSize: 15, weight: .bold)
            
            let fontAttributes = [NSAttributedString.Key.font: font]
            let title = NSLocalizedString("Send", comment: "")
            let size = (title as NSString).size(withAttributes: fontAttributes)
            
            $0.setSize(CGSize(width: size.width + 10, height: 36), animated: false)
            $0.title = title
            $0.titleLabel?.font = font
        }

How can I change the title of the button and adapt its width automatically?

**Comment by nathantannar4** [comment]
Hey @sarbogast your halfway there. You also need to call the `setRightStackViewWidth` since the allowable width is also fixed. Then the items in the stack view can expand. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sarbogast** [comment]
Thanks, that worked.
