### ISSUE TITLE
Color of messages

### ISSUE THREAD

**Issue by hhoangna** [nathantannar4/InputBarAccessoryView#70]
Could you support or create an example for color of messages.
It must be gradient color look like new feature of Messenger like this:
![messenger-4-group-chat-3-ios](https://user-images.githubusercontent.com/26923574/59575623-70bfb300-90e6-11e9-987c-26cc85ab5b16.png)

**Comment by nathantannar4** [comment]
Did you mean to make this a MessageKit issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
Could be a feature?

**Comment by nathantannar4** [comment]
Please post on the features issue on MessageKit. This is separate from the InputBarAccessoryView

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
