### ISSUE TITLE
add UICollectionView in topStack 

### ISSUE THREAD

**Issue by hendyevan** [nathantannar4/InputBarAccessoryView#72]
Hi, im trying to add custom UI in inputBar. When i'm add custom label on topStackView it's shows up. But when i add custom UICollectionView it's not shows up.

`topStackView.addArrangedSubview(MessageTemplateView(frame: CGRect(x: 0, y: 0, width: 130, height: 40)))`

Custom UICollectionView:
```
class MessageTemplateView: UIView, UICollectionViewDataSource, UICollectionViewDelegate {
    
    private let reuseIdentifier = "TemplatesCell"
    var templates: [String] = []
    var collectionView : UICollectionView!
  
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
        
        addSubview(collectionView)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    override var intrinsicContentSize: CGSize {
        return CGSize(width: UIView.noIntrinsicMetric, height: 40)
    }
    
    private func setup(){
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .horizontal
        collectionView = UICollectionView(frame: CGRect.zero, collectionViewLayout: layout)
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        collectionView.delegate = self
        collectionView.dataSource = self
        collectionView.register(UINib(nibName: "TemplatesCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: reuseIdentifier)
        collectionView.backgroundColor = .yellow
        print("templates")
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfSections section: Int) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 4//templates.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as! TemplatesCollectionViewCell
        cell.backgroundColor = .cyan
        print("templates cell")
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: 130, height: 40)
    }
}

**Comment by nathantannar4** [comment]
It looks like you haven't defined a height. Even though you intialize it with a frame when it comes to the stack view laying out the view it will be based on intrinsic content size. Either provide a height constraint or override the intrinsic content size with the height you want. 

Also, I don't recommend giving the view top/left/bottom/right constraints. The stack view is set up to fill it to the edges. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hendyevan** [comment]
Hi @nathantannar4 when i override intrinsic content size, the collection view are now shows up.
But the datasource are not called. My collectionview cell did not shows up.

**Comment by nathantannar4** [comment]
For the intrinsic size width, try `UIView.noIntrinsicMetric`. You shouldn't use `frame.width` for an intrinsic size since that size would determine the width. The size likely being returned right now is a width of 0 so your cells are never rendered. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hendyevan** [comment]
Im using your suggesstion `UIView.noIntrinsicMetric`, but it's still the same. There are no collectionview cell that shows up.

**Comment by nathantannar4** [comment]
I just noticed your code. Are you ever actually setting the frame of your collection view? I see you subclasses UIView rather than UICollectionView. So your collection views frame is .zero

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hendyevan** [comment]
Ah, my bad, forgot to set collection view frame. Now it's shows up. Thanks for you help :D
