### ISSUE TITLE
Top Stack View configure height

### ISSUE THREAD

**Issue by hhoangna** [nathantannar4/InputBarAccessoryView#73]
I have an custom UIView with height = 80. I added it into topStackView. But height of topStackView is smaller. How can I set new value for topStackView's height?

**Comment by nathantannar4** [comment]
Top and bottom stack views are self sizing based on subviews intrinsic (or required by constraints) size. Left and right stack views are this way as well except they have a width constraint

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
