### ISSUE TITLE
How to change inputTextView text color? 

### ISSUE THREAD

**Issue by es0o** [nathantannar4/InputBarAccessoryView#74]

**Comment by nathantannar4** [comment]
You can use the `textColor` property. If you are using the `AutocompleteManager` you will need to modify the `defaultTextAttributes` since it uses attributed strings

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by es0o** [comment]
autocompleteManager.defaultTextAttributes = [.font: UIFont(name: "JannaLT-Regular", size: 17), .foregroundColor: Theme.current_theme.tint] //to change text color
