### ISSUE TITLE
Window level issue

### ISSUE THREAD

**Issue by mixo44** [nathantannar4/InputBarAccessoryView#77]
Hi. There is a bug connected with window level. 

To reproduce the bug just put this code inside of any view controller's `viewDidLoad` that overrides `inputAcessoryView` (e.g. inside of `InputAccessoryExampleViewController` in the example project):

```
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    UIApplication.shared.delegate!.window!!.windowLevel = .statusBar + 1
}
```

Result: When the window's level changes the input bar just disappears.

**Comment by nicolas-bonnet-weforum** [comment]
@mixo44 Did you find a solution for this?

**Comment by nathantannar4** [comment]
This probably applies to any input accessory view. You probably need to go the subview route.

**Comment by fukemy** [comment]
same problem here, after SVPogressHUD dismiss then the input bar go disapear. plz help

**Comment by nathantannar4** [comment]
This issue has become stale/outdated. Please re-open if desired.
