### ISSUE TITLE
Separator line is too thick

### ISSUE THREAD

**Issue by danqing** [nathantannar4/InputBarAccessoryView#83]
It seems the separator line is 1pt tall, and not 1px. This makes it 2 or 3 pixels tall (Retina display). Can we make it only 1px tall?

Thank you for this great library!

**Comment by nathantannar4** [comment]
There is a height property you can mutate. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danqing** [comment]
Great to know. Still, do you think it makes sense to default to 1px? That's the system norm I believe.
