### ISSUE TITLE
Adding custom view overlapping keyboard to be shown on InputBarButtonItem tap

### ISSUE THREAD

**Issue by jakubwarchol** [nathantannar4/InputBarAccessoryView#84]
Does InputBarAccessoryView support this? I'm trying to replicate Messenger's / iMessage feature. When you tap images / stickers / something else a view covers the keyboard giving you a selection. 

I've been trying to do it myself by adding the view to the keyboard's window. It works fine when keyboard is already shown. I just get it's frame and add a view to it's window. I'm having trouble getting it to show smoothly from the bottom alongside keyboard when keyboard was not shown yet. I get the frame and animation options from the `keyboardWillChangeFrame` notification and animate frames but the view keep showing up from the top left corner of the screen. I've been trying to call `layoutIfNeeded` on keyboard's window but no luck.

**Comment by nathantannar4** [comment]
Sorry I've never tried to place a view over the keyboard before. I'm not sure how this is achieved. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danqing** [comment]
I'm interested in the reverse, namely that having a view **under** the keyboard, like in the case of Telegram:

![IMG_68489F383613-1](https://user-images.githubusercontent.com/5134133/71103654-6eedbe00-21f5-11ea-86ef-1b106951206a.jpeg)

Here what happens is that the keyboard slide down to reveal a view under the input bar. Facebook Messenger seems to go with this approach too. Is this something achievable with this library @nathantannar4 ?

**Comment by eliburke** [comment]
@danqing I'm pretty sure that's what @jakubwarchol was talking about. Apple calls it the [Input Accessory View](https://developer.apple.com/documentation/uikit/uiresponder/1621119-inputaccessoryview).

**Comment by danqing** [comment]
@eliburke yes I'm aware it's input accessory view (as indicated by the name of this library). We are trying to achieve similar but different things. If you have Telegram installed, you see the sticker view is _behind_ the keyboard. iMessage on the other hand is what @jakubwarchol said - stickers appear on top of the keyboard, which most likely is in the keyboard's window as he said.

**Comment by Kaspik** [comment]
I believe custom implementation is needed here. PR with Example and tests would be welcome tho, but it's currently out of scope of this project. :)

**Comment by WineKai** [comment]
@danqing i need this !! Have you already done that?

**Comment by Kaspik** [comment]
Just FYI, we use MessageKit and InputBarAccessoryView and we have completely the same functionality on our project. There is no change needed from this framework so I'm closing this. Example would be still nice to add.
