### ISSUE TITLE
bottomStackView heightAnchor not work everytime

### ISSUE THREAD

**Issue by deankai** [nathantannar4/InputBarAccessoryView#85]
I add an InputBarButtonItem on the leftStackView, to have its own action to control bottomStackView height, however, it only works first two times, means that it can only open and close once like this:
at begining:

<img width="239" alt="螢幕快照 2019-09-05 下午12 20 42" src="https://user-images.githubusercontent.com/25227326/64311698-a2eefb80-cfd7-11e9-9304-f9838007ae90.png">
then click once:
<img width="407" alt="螢幕快照 2019-09-05 下午12 20 54" src="https://user-images.githubusercontent.com/25227326/64311729-bf8b3380-cfd7-11e9-8df9-de972c263f79.png">
then it will close:
<img width="239" alt="螢幕快照 2019-09-05 下午12 20 42" src="https://user-images.githubusercontent.com/25227326/64311698-a2eefb80-cfd7-11e9-9304-f9838007ae90.png">

then nothing happened

and here is my code:

```
if isAddBtnClick {
            isAddBtnClick = false
            bottomStackView.heightAnchor.constraint(equalToConstant: 0).isActive = true
            for view in bottomStackView.arrangedSubviews {
                bottomStackView.removeArrangedSubview(view)
                view.removeFromSuperview()
            }
        } else {
            isAddBtnClick = true
            let firstStackView = UIStackView(frame: .zero)
            firstStackView.addArrangedSubview(calendarBtn)
            firstStackView.addArrangedSubview(personBtn)
            firstStackView.addArrangedSubview(giftBoxBtn)
            firstStackView.addArrangedSubview(bellBtn)
            firstStackView.distribution = .equalCentering
            firstStackView.alignment = .center
            firstStackView.spacing = 20
            let secondStackView = UIStackView(frame: .zero)
            secondStackView.addArrangedSubview(blackListBtn)
            secondStackView.addArrangedSubview(temp0Btn)
            secondStackView.addArrangedSubview(temp1Btn)
            secondStackView.addArrangedSubview(temp2Btn)
            secondStackView.spacing = 20
            secondStackView.distribution = .equalCentering
            secondStackView.alignment = .center
            bottomStackView.addArrangedSubview(firstStackView)
            bottomStackView.addArrangedSubview(secondStackView)
            bottomStackView.heightAnchor.constraint(equalToConstant: 180).isActive = true
            
        }
```

any suggestion can be helpful. 
Thanks

**Comment by nathantannar4** [comment]
I would advise against setting a constraint on the `bottomStackView`, it will size itself based on the needs of its subviews so instead apply height constraints to `firstStackView` and `secondStackView`

**Comment by deankai** [comment]
> I would advise against setting a constraint on the `bottomStackView`, it will size itself based on the needs of its subviews so instead apply height constraints to `firstStackView` and `secondStackView`

Thanks, man! It works.

**Comment by fukemy** [comment]
sorry but can we did it with leftstackview?
