### ISSUE TITLE
Input Bar Accessory View auto disappear when app enterBackground

### ISSUE THREAD

**Issue by hhoangna** [nathantannar4/InputBarAccessoryView#86]
I'm using tab bar controller contains 4 view controllers. I push navigation controller from one of them to chat view controller which include your Input Bar Accessory View (have been customized).
Stand on chat view controller, after i switch to other application or let app enter background, when i reopen app input bar disappear.
I have try add self.becomeFirstResponder() but nothing change.

**Comment by nathantannar4** [comment]
Hmm that sounds odd. Did you try calling `becomeFirstResponder()` on the `InputTextView`? Or are you using some custom container controller?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hhoangna** [comment]
Nope. I use chat view controller of MessageKit and my input bar customized from your input bar acessory view.

**Comment by aligermiyanoglu** [comment]
+1
