### ISSUE TITLE
Make translucent view adaptive for iOS 13

### ISSUE THREAD

**Issue by danqing** [nathantannar4/InputBarAccessoryView#88]
Currently the blur doesn't work in dark mode for iOS 13 since the effect is not adaptive.

https://github.com/nathantannar4/InputBarAccessoryView/blob/8a1a02a2a7bb715cf928e2b2a0d8719f250b0ca3/Sources/InputBarAccessoryView.swift#L63

**Comment by fukemy** [comment]
hi. how did u fix this?
