### ISSUE TITLE
InputBarAccessoryView disappeared after swipe dismiss from QuickLook on iOS 13

### ISSUE THREAD

**Issue by denniscyoung** [nathantannar4/InputBarAccessoryView#90]
We implemented the InputBarAccessoryView in a messaging view controller, it uses Apple's QuickLook to preview images.  Once an image is opened in QuickLook, i can swipe dismiss the image or use the Done button to dismiss the image.  If i use the swipe dismiss, the inputBarAccessoryView disappears from the messaging view controller, but will slowly animated back to the view controller after 100 seconds; this problem is only reproducible on iOS 13.  Tapping the Done button in the QuickLook view doesn't cause this problem.   Any suggestion is appreciated, thanks.

**Comment by nathantannar4** [comment]
Not sure. Unfortunately I don’t have any experience with Quick Look. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lsmilek1** [comment]
Hello, I noticed in iOS 13 that keyboard notifications are fired multiple times and even with wrong endFrame size. This is setting collection bottom inset multiple times and causing a jumpy UI especially with collection view with sticky headers. Perhaps it is related. Any idea how to prevent multiple notification? I suspect that TextView resign first responder, what is then switched to collection view controller and back again...? Thanks

**Comment by p-barabas** [comment]
Hi, is there any solution for this issue?

**Comment by x401om** [comment]
Hi guys! I faced pretty the same issues using `InputBarViewController`. Check [my answer](https://stackoverflow.com/a/63453760/1504959) on StackOverflow, hope it will help.

**Comment by Kaspik** [comment]
Workaround mentioned above. Closing for now, for other issues, please open new Issue separately.

**Comment by harry1064** [comment]
is this issue resolved?

**Comment by harry1064** [comment]
Found that UIKit is adding animation on the UIInputSetHostView which is the superview where inputAccessoryView is added by the UIKIt. 
```
 <UIInputSetHostView: 0x124e410f0; frame = (0 623; 375 44); animations = { position-3=<CABasicAnimation: 0x282d07400>; position=<CABasicAnimation: 0x282dd9280>; }; layer = <CALayer: 0x282d16ca0>>
 ```
On examining the animation, found that the duration of the animation is 100s. 
so in the viewDidAppear, I did this workaround.
```
if let animationKeys = self.inputAccessoryView.superview?.layer.animationKeys(), !animationKeys.isEmpty {
    self.inputContainerView.superview?.layer.removeAllAnimations()
}
```
