### ISSUE TITLE
Subclass of AttachmentCell deleteButton not responding.

### ISSUE THREAD

**Issue by mdescalzo** [nathantannar4/InputBarAccessoryView#94]
Working with the AttachmentManager plugin.

When I implement AttachmentManagerDataSource and use a custom subclass of AttachmentCell (DocumentAttachmentCell) and the provided ImageAttachmentCell class, neither cell responds to taps to the deleteButton.  If I disable the AttachmentManagerDataSource and allow the AttachmentManager's default handler generate the cell, the delete button works as expected for ImageCells, but not for the default AttachmentCell.

**Comment by nathantannar4** [comment]
This issue has become stale/outdated. Please re-open if desired.
