### ISSUE TITLE
iOS 13 Modal presentation style Dismiss

### ISSUE THREAD

**Issue by ManuelEMR** [nathantannar4/InputBarAccessoryView#96]
When the user drags the presented ViewController with has the InputBarAccessoryView, the InputBarAccessoryView hides itself.

Even if the user didn't finish the drag down gesture to completely dismiss the modal ViewController, this causes the InputBar to disappear and never to show again.

How can this be fixed?

**Comment by nathantannar4** [comment]
Try calling becomeFirstResponder on either the view controller or the text view In the input bar on viewDidAppear

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ManuelEMR** [comment]
Thanks
